### ISSUE TITLE
about KITTI Odometry Benchmark Velodyne point clouds (80 GB)

### ISSUE THREAD

**Issue by amiltonwong** [PRBonn/semantic-kitti-api#1]
Hi, all,

Thanks for the package and the labels annotations. Currently, I'm testing semantic-kitti-api. However, I cannot access the kitti website for downloading the dataset ` KITTI Odometry Benchmark Velodyne point clouds (80 GB)`. Can you access it? 

THX!

**Comment by amiltonwong** [comment]
It's fixed now. Thx!

**Comment by Jiawei-Shen** [comment]
Hi, the link doesn't work again, could you share the dataset? THX!

**Comment by jbehley** [comment]
Seems like it works now again
