### ISSUE TITLE
index -2147483648 is out of bounds for axis 0 with size 64

### ISSUE THREAD

**Issue by liujw-tobias** [PRBonn/semantic-kitti-api#100]
I use my own point cloud data，and  convert PCD into bin file for testing and output labels, but I can't visualize it. What's the reason?

Sematickitti's data visualization succeeded

error：index -2147483648 is out of bounds for axis 0 with size 64

**Comment by willy8898** [comment]
I met the same problem, too. In my situation, the error comes from the range image projection. 
Maybe you should comment the range image visualization in auxiliary/laserscanvis.py.
![image](https://user-images.githubusercontent.com/62001022/165472201-d49d5ac0-30a1-4928-b586-4b600f33a766.png)
![image](https://user-images.githubusercontent.com/62001022/165472237-56492cf0-aa2c-4d5b-a4c6-c431bf52c4fb.png)

Then, recheck your data and labels.
If the point xyz and label are correct, you can successfully get the result.
![image](https://user-images.githubusercontent.com/62001022/165472941-13adf920-f243-4b50-90a1-78d3dfe0a28a.png)

In my situation, I found that I should use ".astype('int16')" before saving the downsampling 16-beam point cloud.
reference from here: https://stackoverflow.com/questions/10535687/write-a-raw-binary-file-with-numpy-array-data

**Comment by l9761116** [comment]
Hey! I'm also on a project of my own dataset. So I'm very interest in how you get your predictions. Which net did you use and did you trained on it? May I have some suggestions?
