### ISSUE TITLE
about mini dataset

### ISSUE THREAD

**Issue by WYHbxer** [PRBonn/semantic-kitti-api#101]
When I trained segcontrast on semantic-kitti, I find it takes a lot of time to train.
Is there a mini semantic-kitti dataset for training and testing algorithms? just list Imagenet-100?

**Comment by jbehley** [comment]
Officially, there is no small size part of the dataset that we endorse. You are free to use only part of the sequences or subsample the scans yourself.

**Comment by WYHbxer** [comment]
> Officially, there is no small size part of the dataset that we endorse. You are free to use only part of the sequences or subsample the scans yourself.

Thanks
