### ISSUE TITLE
Test Set 11-20

### ISSUE THREAD

**Issue by L-Reichardt** [PRBonn/semantic-kitti-api#102]
Hello,

I found the match of raw KITTI Odometry data to the train set. Is there a similar list for the test set? Additional data would be very useful for my research.

Best Regards,
L

Train Set :
Nr.     Sequence name     Start   End
---------------------------------------
00: 2011_10_03_drive_0027 000000 004540
01: 2011_10_03_drive_0042 000000 001100
02: 2011_10_03_drive_0034 000000 004660
03: 2011_09_26_drive_0067 000000 000800
04: 2011_09_30_drive_0016 000000 000270
05: 2011_09_30_drive_0018 000000 002760
06: 2011_09_30_drive_0020 000000 001100
07: 2011_09_30_drive_0027 000000 001100
08: 2011_09_30_drive_0028 001100 005170
09: 2011_09_30_drive_0033 000000 001590
10: 2011_09_30_drive_0034 000000 001200

**Comment by jbehley** [comment]
sorry for the delay.

no, by design from the original authors (Geiger et al.), there is no match with sequences from the raw sequences available for the testset.

**Comment by L-Reichardt** [comment]
@jbehley  Thank you for your response.
