### ISSUE TITLE
[HELP NEEDED!] How to relate Semantic KITTI frames to KITTI Depth frames??

### ISSUE THREAD

**Issue by tricostume** [PRBonn/semantic-kitti-api#103]
Hello,

I would like to know how to map each of the depth maps provided in the KITTI Depth frame to the Semantic KITTI Dataset? With this I could have dense Semantic KITTI information for some frames and also the pose from Odometry sequences. 
Thank you!

**Comment by jbehley** [comment]
I don't know about the depth dataset specifically, but there might be no 1-to-1 matching between the dataset (for the odometry dataset, there is a README file that says which sequences are from the raw data, but I don't know if this is also available for the depth data. And it is definitely not available for the test data).

However, as far as I know, are the depth frames for the ground truth anyway generated from the LiDAR information.
