### ISSUE TITLE
Running error in Google Colab

### ISSUE THREAD

**Issue by E4CEeg** [PRBonn/semantic-kitti-api#105]
Hello, Thank you for the great work.
I have tried visualize_mos.py in GoogleColab. However I have encountered this error.

WARNING: could not connect to display 
WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Have you tried to run this app in Google Colab? Is there any way to run visualize_mos.py in GoogleColab?

Thank you.

**Comment by Body123** [comment]
did you solve the problem ,dear??
