### ISSUE TITLE
Could you provide the competition bundle for Codalab?

### ISSUE THREAD

**Issue by bbbbubble** [PRBonn/semantic-kitti-api#107]
Hi! Thank you for this amazing work!
I am now working on a 3D dataset and planning to hold a semantic segmentation competition on Codalab. In order to do that, a competition bundle is needed. I'm new to CodaLab, may I ask you to provide your competition bundle (test set gt removed) as an template for similar competitions? That will help me a lot!
Thank you very much, looking forward to your reply!
![image](https://user-images.githubusercontent.com/45709295/199054566-9af4a4cc-b45a-4d79-bc0a-3f892ab2ab2e.png)

**Comment by jbehley** [comment]
Hi, sorry for the delay, but we are currently a bit busy.

The simplest way to also get the dataset on codalab and scripts is to first upload these separately. Then, it just referring to this via the hashes in the script. Here is the competion.zip which I used for the updated semantic segmentation competition: [competition.zip](https://github.com/PRBonn/semantic-kitti-api/files/9962903/competition.zip)

After setting up the competition, you can also change the most of the information, but note that you cannot modify the leaderboard configuration any more! Best is to check if everything works by uploading an example submission.

Hope that helps.

**Comment by jbehley** [comment]
seems to be solved? (closed for now.)
