### ISSUE TITLE
Request for approvement of the SemanticKITTI registration

### ISSUE THREAD

**Issue by kebijuelun** [PRBonn/semantic-kitti-api#112]
We submitted an account application last Friday, but we haven't received any approval information yet.
We are very anxious to submit a version of test results on Semantic KITTI（SSC） recently. Please help us approve it as soon as possible.

Thanks for your help.

**Comment by jbehley** [comment]
There are no open request in the new competition. Please check if you registered in the correct competition. Since Summer 2022 it's not possible to submit on the old servers.

**Comment by kebijuelun** [comment]
> There are no open request in the new competition. Please check if you registered in the correct competition. Since Summer 2022 it's not possible to submit on the old servers.

thanks for your reply, but I double checked that I have push the register button on the Semantic Scene completion page：

![image](https://user-images.githubusercontent.com/29164878/212614704-83a03dff-4248-4bce-a3af-56edac47a0b6.png)

and I also received a email in last friday:

![image](https://user-images.githubusercontent.com/29164878/212614815-558c69c3-d6be-42dc-982f-1241bf73f3ae.png)

I also use another personal email (liuweizhou000@126.com) for registration, and receive a 
reject email:
![image](https://user-images.githubusercontent.com/29164878/212615928-b7d8cd93-c58d-4b39-bcc1-88aafa10ee86.png)
I wonder if you can approve the personal email for us to submit our results? or how can I do a success registration with our company email?

I hope you can check it again. 
Thanks !

**Comment by jbehley** [comment]
You should now have access with your company email address. hope that solves the problem.
