### ISSUE TITLE
Instance ID and Semantic ID problem

### ISSUE THREAD

**Issue by HMX2013** [PRBonn/semantic-kitti-api#114]
The point that has same Instance ID and Semantic ID belongs to a object.  I use this criterion to clustering point cloud. However, I meet some problems. 

When I just load the point cloud that belongs to "Car", I got the correct result, see the first figure. 
But when I load other class such as "building", I got the wrong result, see the second figure.  It seems that the two object  far away that has same semantic ID and Instance ID. I think their Instance ID should be different. I have spent many time but still cannot solve this problems. 
Hope you can help me through this, looking forward to your reply! Thanks.

The following is the code I read the labels
uint16_t semantic_id = label[i] & 0xFFFF;
uint16_t instance_id = label[i] >> 16;

The following is the criterion I use to judge whether two points belongs same object
if (pt_from.semantic_id == pt_this.semantic_id && pt_from.instance_id == pt_this.instance_id
{
..................................
}

[Screenshot from 2023-02-17 11-30-35](https://user-images.githubusercontent.com/105980724/219542931-dfcae519-7880-496f-beb6-d67dd18838b0.png)

![Screenshot from 2023-02-17 11-32-56](https://user-images.githubusercontent.com/105980724/219544058-3a1205af-9127-4e18-b2db-f2f1e633d2fd.png)

**Comment by jbehley** [comment]
Note that we have stuff and thing classes. We decided to have instances only for traffic participants, i.e., car, bicyclist, pedestrian, etc.

For is building is a stuff class, thus, there is no distinction between different instances.

Hope that clarifies the issue.

**Comment by HMX2013** [comment]
Thank you, Maybe I can just use the dsitance instead of instance id to distinguish the stuff class.
