### ISSUE TITLE
Problem about the kitti pose.

### ISSUE THREAD

**Issue by Xiaxia1997** [PRBonn/semantic-kitti-api#115]
From https://github.com/PRBonn/semantic-kitti-api/issues/78, we can get
The poses.txt is given in the camera coordinate system, Tr is the extrinsic calibration matrix from velodyne to camera.
In this case,
 `Pose_velodyne = Tr_inv * Pose_camera`. But the code is` poses.append(np.matmul(Tr_inv, np.matmul(pose, Tr))) ` 
which means `pose = Tr_inv * Pose_camera *Tr`. I'm confused about it.

**Comment by jbehley** [comment]
The points are given in the coordinate system. the poses in the coordinate system of the camera. Thus, one first needs to go from lidar to camera, apply the camera poses, and then back to lidar coordinates to have the points again in the lidar coordinate system.

hope that helps.

**Comment by Xiaxia1997** [comment]
@jbehley So the camera poses means current camera position respect to the initial camera position.(From [here](https://stackoverflow.com/questions/72492141/are-the-elements-of-the-pose-matrix-in-kitti-odometry-dataset-absolute-or-relati)). In this way, we get the points from current lidar coordinate system to initial lidar coordinate.  Did I get it?
Since [from here](https://github.com/PRBonn/SHINE_mapping/issues/9), the writer explain the the pose as transformation from lidar to world coordinate system, I'm confused about it.

**Comment by jbehley** [comment]
If you have further issues with the transformation or need some additional explanation, let me know (and re-open the issue). However, I close the issue for now.
