### ISSUE TITLE
Panoptic Segmentation Benchmark min_points

### ISSUE THREAD

**Issue by YilmazKadir** [PRBonn/semantic-kitti-api#116]
When you evaluate the predictions for the Panoptic Segmentation competition, do you also ignore instances that have less than 50 points similar to this? https://github.com/PRBonn/semantic-kitti-api/blob/439877833a0ca87c79643aef4c3561a1cb3a96bc/auxiliary/eval_np.py#L155

**Comment by jbehley** [comment]
We use the exact same script for evaluation on the Codalab servers. Therefore, we only consider segments with more then 50 points.
