### ISSUE TITLE
The difference between real and predictive labels

### ISSUE THREAD

**Issue by xpzbph** [PRBonn/semantic-kitti-api#118]
Hello, first of all thank you for this great program, it helped me a lot. I have a question how to visualize the labels with right predictions and wrong predictions in two different colors? Looking forward to your reply!

**Comment by xpzbph** [comment]
> Member
I tried to visualize it myself before your reply, using the real label minus the predicted label, and creating a ndarray of the same length, setting the value at the corresponding position to 299 if the labels are the same, and setting the value at the corresponding position to 300 if they are different, and setting the bgr corresponding to 299 and 300 in the yaml file, which in turn generates a new .label file, and to visualize it. But the result is not quite correct, I wonder if you know what is wrong with my approach?

**Comment by xpzbph** [comment]
@jbehley I tried to visualize it myself before your reply, using the real label minus the predicted label, and creating a ndarray of the same length, setting the value at the corresponding position to 299 if the labels are the same, and setting the value at the corresponding position to 300 if they are different, and setting the bgr corresponding to 299 and 300 in the yaml file, which in turn generates a new .label file, and to visualize it. But the result is not quite correct, I wonder if you know what is wrong with my approach?

**Comment by jbehley** [comment]
I would simply read the labels from the prediction and the corresponding label from the ground truth. Then draw it accordingly (see the vispy example that we have.) You can also have a look at Open3D if this is simpler to use.

I just provide the data and the visualization was more a service than the main thing that we want to distribute.

**Comment by xpzbph** [comment]
Thank you for your reply, I think I should be able to find a solution
