### ISSUE TITLE
about visualization

### ISSUE THREAD

**Issue by cama36** [PRBonn/semantic-kitti-api#119]
Hi, I want to use visualize.py to view predicted labels, but I also want to display the true labels at the same time. Can you tell me how to do that?Thank you

**Comment by jbehley** [comment]
Not sure if I can help here, since it highly depends on what you want to do; please have a look at https://vispy.org/, which we used for visualizing the points. There is also a way to have two views of the same point cloud and link them. However, you can also use Open3D to visualize labels.

**Comment by cama36** [comment]
Thanks for your reply. In my task, I just wanted to visualize both truth labels and prediction labels. For example, the truth TAB is displayed in the left window and the prediction TAB is displayed in the right window. Is that OK?
