### ISSUE TITLE
Competition SemanticKITTI: Semantic Segmentation submission fail

### ISSUE THREAD

**Issue by mellody11** [PRBonn/semantic-kitti-api#120]
Hello, I prepared for every thing and run the code validate_submission.py and got the full tick

 ============ segmentation ============ 
  1. Checking filename.............. ✓
  2. Checking directory structure... ✓
  3. Checking file sizes............ ✓

However, when I summit on the [website](https://codalab.lisn.upsaclay.fr/competitions/6280#participate-submit_results), it reports error with:

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpYbVuqZ/run/program/evaluate_semantics.py", line 171, in 
    assert(len(label_names) == len(pred_names))
AssertionError

I have no idea about where is the problem.

**Comment by jbehley** [comment]
it means that the number of submitted labels is not the same as we expect. (check that for each sequence that there are the same number of label file as bin files)

**Comment by mellody11** [comment]
Thanks for your reply.

I have already get the result, Thank you.

**Comment by completezealous** [comment]
> Thanks for your reply.
> 
> I have already get the result, Thank you.

I also encountered the same problem as you. How did you solve it
