### ISSUE TITLE
Understanding the semantic kitti dataset. Shape of Label vs Shape of Pointcloud ?

### ISSUE THREAD

**Issue by bisalgt** [PRBonn/semantic-kitti-api#127]
Hi There.

 I recently started looking into the semantic kitti dataset. I am trying to find the corresponding label for each point in the pointcloud.
The approach that I followed was : 
- Loading the "XXXXX.bin" file contained in the velodyne folder using NumPy.
- Reshaping the "pointcloud" to "N x 4" using np.reshape.
- Loading the corresponding "XXXXX.label" using numpy and reading as unsigned int.

The shape of label is not equal to the shape of pointcloud after reshape. But the shape of label is equal to the shape of pointcloud before reshaping. What is the reason?

Can anyone explain me the concepts or point me to the resources where I could understand the difference in shape between the labels and corresponding pointcloud in the semantic kitti dataset?

Thank you in Advance. 

Regards,
Bishal Gautam

**Comment by jbehley** [comment]
the data types are important (points are float32 and labels are uint32); thus:
```python
    scan = np.fromfile(filename, dtype=np.float32)
    scan = scan.reshape((-1, 4))
    ...
    label = np.fromfile(filename, dtype=np.uint32)
```

hope that helps.

**Comment by bisalgt** [comment]
Hi jbehley,

Thank you so much for your quick help. 
I did that. But the shape of  label is not equal to the number of points after reshaping the scanned data.  What might be the reason ? Am I understanding something wrong ?

**Comment by jbehley** [comment]
are the filenames the same? are you reading the complete file?

**Comment by bisalgt** [comment]
Yes. The file names are same. 

- The shape of scan after reshaping is "(124605, 4)"
- The shape of label after reading is "(498420,)"

**Comment by bisalgt** [comment]
I am really sorry. Now I checked the file again. I had mistakenly used the name of scanfile to read the label. So, I was reading the scanfile twice instead of labelfile. I corrected it and now its working. This was the reason. Thank you for your quick response jbehley. 


Regards,
Bishal
