### ISSUE TITLE
window background color of a visualization

### ISSUE THREAD

**Issue by shenggebiya** [PRBonn/semantic-kitti-api#128]
Excellent work. How to change the window background color of a visualization to white

**Comment by jbehley** [comment]
Please see `auxiliary/laserscanvis.py` and then I think you have to change the color in the `SceneCanvas`: https://vispy.org/api/vispy.scene.canvas.html

**Comment by shenggebiya** [comment]
Thank you for your help, I made it

**Comment by dafengtian** [comment]
> Thank you for your help, I made it

Hi, shegngebiya. I also want to know how to chage the window background color of a visualization. Could you please tell me how to achieve this?

**Comment by dafengtian** [comment]
Thanks, I succeeded. Proceed as follows:
1. Find the vispy installation location
2. Find visipy >> scene >> canvas.py
3.Change bgcolor to white
![Selection_008](https://github.com/PRBonn/semantic-kitti-api/assets/100512884/85a2832e-ffbb-4a58-a021-bd3d6047872b)
