### ISSUE TITLE
Is the points number for each scan is the same?

### ISSUE THREAD

**Issue by DeepDuke** [PRBonn/semantic-kitti-api#129]
Hi, Is the points number in each scan the same value for all scans? 
You know, for a 3D Lidar, if the FOV and resolution are fixed, the points it can get in each scan should be a fixed number.

**Comment by jbehley** [comment]
Note that invalid measurements (e.g., LiDAR beams taking to long to get measured, measurements below a minimum distance, etc.) are filtered out; therefore the number of actual 3d points is different.

Note that we build upon KITTI that provides the 3d data, we only provide the labels and benchmarks.

**Comment by DeepDuke** [comment]
Thank you!
