### ISSUE TITLE
question(s) about the instance labels in the GT 

### ISSUE THREAD

**Issue by niritalkalay** [PRBonn/semantic-kitti-api#130]
looking onto the validation run (08), i have noticed a few things:

1. we only have 1 object labeled "motorcyclist" in this run at  frames 753-1524.
   at the starting frames  the objects seems like mistake in the labeling since it is part of the road,
  but at the near the last frames it is seems to be a real object.

2. for the class "car" , I have looked onto instance id 196.
    and it seems to appear twice in this run : first from frames 0-95, then from frames   1798-1801.
    on both parts, the scene looks similar, it is possible that  in 1798-1801 we returned to the same place as in 0-95?
    if so,  how do you suggest to evaluate the track quality in such case, since there a lot of time has passed , after the first    appearance of this objects. if we count the Id-switch in this case it will go up.  
  I am also not sure what it means for the rest if the labeling.do we expect objects instance id to return? what is the frequency of such cases?

**Comment by jbehley** [comment]
Thanks for your comments. Regarding your questions:

1. I haven't looked into the sequence right now, but there might be still some labeling errors even though we tried to minimize these by a thorough revision of the sequences. (In the IJRR article, we have also some statistics on how much the labels changed). However, these errors should be in the low single-digit percentage range.

2. Yes, instance id's can reappear if there was a loop closure and the cars are static. A loop closure is a part of the map, which gets revisited and our pre-processing with SuMa estimated also loop closures to have a globally consistent map. Therefore, we labeled these also as the same instance. There is even a case (I think sequence 7), where a parked car is not there after the same part is revisited again, but a new car parks at the same spot. Then, I labeled these also two separate instances.

3. Regarding your question of "how to handle this in tracking metrics?": I'm not sure how such situations are handled in the tracking literature, but it might be the right answer to have objects reappear even after a long time. But regarding your question: how often this happens: At every loop closure in a map, all static cars are "re-appearing".  Several sequences (often used in place recognition) are here extreme cases, where the car drives the exact same route again (such as Sequence 01, but also Sequence 06).

**Comment by niritalkalay** [comment]
thank you for the answers. 
so, in theory (or maybe not in theory) there can be an example of a parking car turns to a moving-car? what will happen to the instance ID in such case?

**Comment by jbehley** [comment]
as the label would change (from non-moving to moving), it would also get a new instance id. 

However, such cases are very rare and I'm only aware of a single case where I saw such a thing (again, sequence 07 has this where the car returns to that place); In the labeling process, we worked mainly with the loop closed sequences and only if the shape of the care changed significantly, it would be maybe noticed in the instance annotation process.

For other cases, where the car stops in-between (either standing at a traffic light or waiting for a turn, etc.), the whole trajectory is labeled as "moving-car", thus, it would have a single instance id.

**Comment by niritalkalay** [comment]
thank you. 
one last question : 
I also noticed that instance label ID is unique for each class, but not unique for all classes. 
for example, in seq08, 
we have instance label =2 for class "car" in frames  3087 -3199 
and instance label =2 for class "moving-car" in frames 0-37

but when running the evaluation code, say the '4dpanoptic.py' code or the 'evaluate_panoptic.py' of this repo,  
when we load the segmentation data , we use mapping, so the "moving-car" and the "car" class gets united into a single class, but  then the label remains the same, so we think that they are the same instance object, which clearly they are not.

**Comment by jbehley** [comment]
You are right, that instances are only unique when you consider label + instance id.

Note the way that we use the instance ids here:

https://github.com/PRBonn/semantic-kitti-api/blob/25688277360a265a8983af47e48fa19dfdec069e/evaluate_panoptic.py#L166-L169

While the classes are remapped, the instances are taken from the full 32 bits of the annotation.

**Comment by niritalkalay** [comment]
yes, you are right.
but this is not case for the for the 4dpanoptic.py:

![image](https://github.com/PRBonn/semantic-kitti-api/assets/36958906/b2d63824-64c5-469d-a2fe-66b28b342019)

but i will try to change this locally  and see. 

thank you for the fast reply!

**Comment by jbehley** [comment]
I'm not 100% sure; but I remember that we talked about this (with Mehmet & Aljosa) and checked, but for LSTQ the matching is done differently as there also moving vehicles have to be accounted for. So not sure if it makes a difference in the end. 

They might know more about this.
