### ISSUE TITLE
Understanding poses.txt

### ISSUE THREAD

**Issue by barzanisar** [PRBonn/semantic-kitti-api#133]
Hey! I need help understanding poses.txt. Is it pose of the camera with respect to world frame?

**Comment by jbehley** [comment]
it's the normal KITTI odometry convention, i.e., the camera pose of the left camera as described in the devkit of the KITTI odometry benchmark. While it's a bit inconvenient, we decided to keep it consistent with the original dataset.

Thus, you have always to pre-multiply the LiDAR-to-camera pose (lets call it $\mathbf{Tr}$) and post-multiply the transformation from camera-to-LiDAR, i.e., $\mathbf{Tr}^{-1}$ to get the LiDAR pose: $\mathbf{Tr}^{-1} \cdot \mathbf{T}_i \cdot \mathbf{Tr}$

Hope that helps.

See also the discussion in various other issues (#115, #78, #39, etc.), where you can maybe further information.

**Comment by jbehley** [comment]
It seems like this should be solved. If you have further questions or still a problem, please, re-open the issue.
