### ISSUE TITLE
Request about semanticKITTI dataset

### ISSUE THREAD

**Issue by KangHyunwoogi** [PRBonn/semantic-kitti-api#135]
Hello, 

Is it possible to obtain any part of the rosbag file recorded during the acquisition of semanticKITTI data? 
I need data acquired with an HDL 64-channel lidar. 

Thank you.

**Comment by jbehley** [comment]
We only provide a link to the original data. As far as I know, the original data is only available as binary file. However, there are some people converting (or writing a ROS node) that provides ROS messages:

https://github.com/tomas789/kitti2bag
https://github.com/ethz-asl/kitti_to_rosbag
https://idorobotics.com/2019/05/29/converting-the-kitti-dataset-to-rosbags/

But writing a ROS node that reads the directory should not be so difficult.

Anyway. We will not provide this functionality.

**Comment by jbehley** [comment]
I think this issues seems to be resolved. If you have further questions or concerns, please open the issue again.
