### ISSUE TITLE
Error labeling problem in voxel datasets：08：000000

### ISSUE THREAD

**Issue by dzrdzrdzr** [PRBonn/semantic-kitti-api#137]
In 08package-000000pic shown that there have no long strip occupancy in the middle of road. But it does in voxel.
![000000](https://github.com/PRBonn/semantic-kitti-api/assets/104069847/2493c671-2466-4e91-a01e-8ea9a4cdd408)
![image](https://github.com/PRBonn/semantic-kitti-api/assets/104069847/6f985cfc-9a04-4329-bda5-93dd51d3e8d8)
how do this happen 
what is it in voxel

**Comment by jbehley** [comment]
It's the way we decided to aggregate the data. It's the moving cars that appear here. These we call "spatio-temporal tubes" and represent the occupied space of the moving cars.

We have point-wise moving labels, which means one could also generate this data without the moving vehicles (but we currently didn't execute it).

We are currently evaluating if we also provide a benchmark with the moving cars removed, in light of the increasing interest of the community in occupancy estimation. But currently we are not having own research going in this direction and therefore we have no end-user in our department right now.

**Comment by jbehley** [comment]
There seems to be everything resolved, therefore, I close this issue.

If you still have questions, then simply reopen the issue.
