### ISSUE TITLE
About the inability to access the http://www.semantic-kitti.org/ website.

### ISSUE THREAD

**Issue by OYgreat-river** [PRBonn/semantic-kitti-api#139]
Hello,

 thank you very much for your work on Semantic KITTI. This project is currently a crucial benchmark in the field of point cloud segmentation. However, recently, I have been unable to access the website http://www.semantic-kitti.org/. I would like to inquire if you have any information on the reason for this. Looking forward to your reply. Thank you!

**Comment by SM1991CODES** [comment]
I have also faced this issue recently.

**Comment by jbehley** [comment]
The website is up again; sorry for the trouble.
