### ISSUE TITLE
Question About Manually Loop Closed Trajectories 

### ISSUE THREAD

**Issue by Cedric-Perauer** [PRBonn/semantic-kitti-api#140]
Dear authors, 

thank you for your great work. In the paper you mentioned using manual loop closure constraints for some sequences.
Based on https://github.com/PRBonn/semantic-kitti-api/issues/39 do I understand correctly that they are already included in the poses.txt ? Which sequences are the ones which include the manual constraints ?

Thank you :)

**Comment by Kin-Zhang** [comment]
Sorry to bother again, But I'm wondering the pose error from SuMA paper is that this one I can cite for SemanticKITTI pose error also? or is it different? [seq 00, 01, 02, 05, 07 I need to check]

![image](https://github.com/PRBonn/semantic-kitti-api/assets/35365764/c980cb4d-abe4-4845-af74-f70046500829)

**Comment by jbehley** [comment]
As mentioned before: The poses from sequences 02, 07, and 20 are not the original SuMa poses; therefore, the reported numbers for 02 and 07 might be different for SemanticKITTI, but I never checked the relative pose error.

(Just as a side note: The relative pose error is determined in relation to a GNSS/IMU and therefore might be affected by drift of the system; I do not claim that the SuMa poses are perfect. However: For annotation purposes, we only cared about having somehow globally consistent point clouds that can be locally well annotated.)
