### ISSUE TITLE
 UserWarning: GPUs

### ISSUE THREAD

**Issue by lxdunan** [PRBonn/semantic-kitti-api#141]
Hello, author. I encountered an error while using visualize_mos.py to visualize the SemanticKITTI dataset. The error message is as follows: vis.run() UserWarning: GPUs can't support floating point data with more than 32-bits, precision will be lost due to downcasting to 32-bit float. warnings.warn(F64_PRECISION_WARNING)

**Comment by jbehley** [comment]
Thanks for the information; Not sure if this affects the visualization.

If you notice something weird, let me know.

I close this issue for now as it should not be a big problem, but we might have to change the datatype of the numpy arrays if this turns out to be a real issue.
