### ISSUE TITLE
Mapping to Detection

### ISSUE THREAD

**Issue by L-Reichardt** [PRBonn/semantic-kitti-api#143]
Hello,

is there a mapping between the KITTI detection dataset and the SemanticKITTI dataset?
I am trying to implement Real3DAug which currently relies on pseudo labeling to provide semantic labels for KITTI-Detection, which would not be necessary if such a mapping exists.

Best Regards,
L

**Comment by jbehley** [comment]
I once checked if there is an overlap via md5 hashes of the images (don't remember if there is any). At least that would be a way to check for overlaps (but I think the test set are at least disjunct)

however one can pretty decently project the lidar measurements in the image and then compute bounding boxes with the instance id of the points. but these are the not necessarily amodal (i.e. also covering the occluded parts) One maybe get such thinks with projecting multiple points in time.

But I never tried this. So no warrenty.

**Comment by L-Reichardt** [comment]
Ok thank you very much for your response.
