### ISSUE TITLE
How to learn custom data 

### ISSUE THREAD

**Issue by smileyr99** [PRBonn/semantic-kitti-api#145]
Hello. Thank you for providing excellent code and algorithms.
I have created a custom dataset similar to the semantic KITTI data.
I added additional label values to the custom data and I'm unsure how to modify the code to train it.
Should I put these additional label values in the data_cfg.yaml file and then train it?
I added a total of three label values, ranging from 21 to 23.
As a beginner, I'm not sure how to proceed, so I would appreciate an explanation.
Thank you very much.

**Comment by jbehley** [comment]
Thanks for your interest in the dataset.

How the training is performed is independent of the dataset itself. The `datacfg.xml` is just relevant for our evaluation scripts, so unrelated to the training itself.

How to train and other stuff is implementation dependent, thus a good starting point might be to look at other people's code, like:

Cylinder3D: https://github.com/xinge008/Cylinder3D
RangeNet++: https://github.com/PRBonn/lidar-bonnetal

or other frameworks with pre-implemented architectures. Again, we do not provide any support for the actual training as we are just providing the data here.

Thus, I close this issue now but feel free to open a new issue if you need help regarding the dataset.
