### ISSUE TITLE
visualize.py  problem 

### ISSUE THREAD

**Issue by baibaijinjin** [PRBonn/semantic-kitti-api#146]
After I used visulaize.py, the program did not report any errors, but it did not react, did not generate any visual interface, did not produce any output, did not terminate. The results are the same on both the semantic-kitti dataset and the dataset made by myself. May I ask why?

**Comment by jbehley** [comment]
Without any specific information, it's hard to diagnose the problem. 

We tested the visualizer only on Ubuntu 18.04 and the specified versions. Any information on your system?

**Comment by jbehley** [comment]
There seems not to much updates here, therefore, I'm closing this now. If you have any further information, I can try to help.
