### ISSUE TITLE
issue about data

### ISSUE THREAD

**Issue by M1n1L** [PRBonn/semantic-kitti-api#149]
Hi first of all i wanna say thank you for your work. I wanna ask about the dataset cause you are proving URL to have my whole data. both KITTI Odometry Benchmark and SemanticKITTI dataset. I don't know what files exactly should I download from the KITTI Odometry Benchmark to add to have my whole data

**Comment by jbehley** [comment]
I guess the issue could be resolved, therefore, I close the issue now. If you still have problems, then just re-open the issue.
