### ISSUE TITLE
out of range labels

### ISSUE THREAD

**Issue by uhseon** [PRBonn/semantic-kitti-api#15]
Hello,

Thank you for sharing great data and awesome codes!

I think that some point labels are out of range. 
For instance, I can find '131076', '16449537', ... in '004070.label' of sequence '08'. 
(I converted label files to cross entropy format using your 'remap_semantic_labels.py')

So, I have some questions.
- I wonder if I did something wrong. 
- If not, how can I deal these out of range labels??
- For competition, are they ignored when computing iou?

I will be waiting for your reply.
Thanks!!

**Comment by jbehley** [comment]
Note that the label is inside the lower 16 bit of the uint32, i.e., value &0xFFFF = label. The upper 16 bit correspond to the instance id, which is available for humans and vehicle, i.e., value >> 16 = instance.

hope that solves your issue.

**Comment by uhseon** [comment]
Oh,, I got it. Everything is clear now. 
Thank you for prompt answer!
