### ISSUE TITLE
“Execution time limit exceeded!” occur

### ISSUE THREAD

**Issue by Wachemanston** [PRBonn/semantic-kitti-api#153]
Hi, thanks for providing the LiDAR dataset.
I submitted the test predictions for single scan semantic segmentation but got the error - “Execution time limit exceeded!”
I also tried to submit the same file (em0729.zip) for the multi-scans task, but I could get the result.
Could you please help solve this problem?

Thank you!
My CodaLab username: ysli

The failure for single scan task:
![image](https://github.com/user-attachments/assets/168df06f-450f-45dc-93db-2b1714dca2f8)

The success in multi-scans task:
![image](https://github.com/user-attachments/assets/0c924d49-cb7f-4433-83ac-968cc472628d)

**Comment by jbehley** [comment]
thanks for the message; as we are relying on the workers from Codalab, it might be that they changed something with the cloud servers that run docker, which now seem to reach the execution limit (scoring did only 90% of the data); I currently increased the execution limit and it seems to be working for your submission (that I just started again).

Let me know if this resolved your issue.

**Comment by Wachemanston** [comment]
Yes, now the status looks great. Thanks for your speedy reply and work!
