### ISSUE TITLE
SemanticKITTI: Moving Object Segmentation- Error: Execution time limit exceeded!

### ISSUE THREAD

**Issue by ccyyu2** [PRBonn/semantic-kitti-api#154]
Hello, I am a participant in the SemanticKITTI: Moving Object Segmentation competition. I have ensured that the .zip file I submitted is correct, but my submissions often fail with the following error message: "Error: Execution time limit exceeded!"

**Comment by jbehley** [comment]
I increased the allowed execution time; it should now work more reliably and not depend so much on which nodes it runs.
