### ISSUE TITLE
Corresponding semantic masks on images

### ISSUE THREAD

**Issue by leblond14u** [PRBonn/semantic-kitti-api#155]
Hi, 

Is there a set of semantically labellized images that are matching the colors of the semantic kitti ground truth point-cloud labels available ? 

Thanks a lot, 
Best,

Hugo

**Comment by jbehley** [comment]
hi hugo,

as far as I know there are now image labels that directly correspond to the LiDAR labels. However, I would guess that by projecting the point cloud labels into the  images and using SAM (or SAM2) with the instance labels per class as prompt should work pretty decently. 

However, I never tried it...so if you go down this route, it would be interesting if you report back how that worked out.

**Comment by jbehley** [comment]
I think the issues seems resolved or at least answered. If you have still questions then don't hesitate to reopen the issue.
