### ISSUE TITLE
Different number of sequences for labels and point cloud frames

### ISSUE THREAD

**Issue by zszz3** [PRBonn/semantic-kitti-api#156]
Hi first of all i wanna say thank you for your work. I want to use sequence 04 as an example，the number of labels is 270 but the number of point cloud frames is 278. and the point cloud is download from the kitti raw data. (https://www.cvlibs.net/datasets/kitti/raw_data.php)
![{F62D3947-144D-4165-9717-28C18347B45A}](https://github.com/user-attachments/assets/60a0190a-a551-40db-b6df-791cafc81818)

**Comment by jbehley** [comment]
Note that we annotated the KITTI odometry scans, which are only a subset of the KITTI raw scans. 

Please see the "Readme" in the KITTI Odometry devkit for the mapping from raw data to odometry sequences. This mapping is also only available for the training set of the KITTI odometry benchmark.

If you downloaded the KITTI odomerty LiDAR data and there is a mismatch... please check if all files have been extracted.

**Comment by zszz3** [comment]
Thanks for your answer, I have found the right solution！
