### ISSUE TITLE
Is the camera calibration model in kitti data set a five-parameter model or an eight-parameter model? 请问kitti数据集中的相机标定模型是五参数模型还是八参数模型？

### ISSUE THREAD

**Issue by Elken-lab** [PRBonn/semantic-kitti-api#157]
Is the camera calibration model in kitti data set a five-parameter model or an eight-parameter model?
请问kitti数据集中的相机标定模型是五参数模型还是八参数模型？

**Comment by jbehley** [comment]
Regarding the camera model, I cannot tell anything. Please have a look at the documentation of the KITTI dataset or try to ask the maintainers of KITTI if they can tell you more about the calibration method.
