### ISSUE TITLE
Can you please offer your SqueezeSeg baseline code?

### ISSUE THREAD

**Issue by BenjaminYoung29** [PRBonn/semantic-kitti-api#18]
Hi, I am interestd at your fantastic dataset and can't wait to test my method on it.  My method is based on SqueezeSeg.  But I haven't project to point cloud myself. Can you release your code projecting the dataset to spherical images and the squeezeseg baseline please? 
Thanks.

**Comment by jbehley** [comment]
Please see https://github.com/PRBonn/lidar-bonnetal, there you find our implementation of squeezeseg, squeezesegv2, and our darknet53Seg.
