### ISSUE TITLE
About submission on the muti scan segmentation on colab

### ISSUE THREAD

**Issue by dante0shy** [PRBonn/semantic-kitti-api#20]
Hi Sir,

When I submitted the submission on the Colab for muti scan, it gave a bug which looks like interval problems. My submission has passed the validation code in this project, so I think there might be some bugs there.

My bug on colab is as below:
```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
usage: ./evaluate_semantics.py [-h] --dataset DATASET
                               [--predictions PREDICTIONS]
                               [--split {train,valid,test}]
                               [--backend {numpy,torch}] [--datacfg DATACFG]
                               [--limit LIMIT] [--codalab CODALAB]
./evaluate_semantics.py: error: argument --codalab: expected one argument
```

**Comment by jbehley** [comment]
Thanks for reporting this problem and I found it. It was a problem with calling the scoring program. It is now fixed.

I just re-run your last submission and delete the failed ones.

I'm closing this issue, since it is no issue any more.
