### ISSUE TITLE
Join the pointcloud data of each sequence in one scene

### ISSUE THREAD

**Issue by medif** [PRBonn/semantic-kitti-api#22]
Hi,
I saw from your paper that you made testing using pointnet ++ and pointnet. 
I need to reproduce the same testing so i have to assemble the data of each sequence to form a whole scene then to cut it into batch. Can i know how did you reorganize the data please?
which code did you use to assemble all sequences in a  whole scene
I will be thankful if you provide with some guidance for the data organization in this case.
Thank you

**Comment by jbehley** [comment]
@medif Does this solve your issue?

**Comment by medif** [comment]
Hi thank so much for your response 
Sorry it still not clear for me, Do you mean you used the whole scans form only one sequence (for example using the 4000 scans in the first sequence) as a training set ?
Thank you

**Comment by jbehley** [comment]
We used all scans from sequence 00 to sequences 10 (without sequence 08) for training. 

There are two different tasks described in the paper: using a single scan or multiple scans as input (5 prior scans). But what you use is your decision.

**Comment by jbehley** [comment]
Do you still have problems? Otherwise, we could close this issue.
