### ISSUE TITLE
Fail to visualize pointcloud

### ISSUE THREAD

**Issue by BenjaminYoung29** [PRBonn/semantic-kitti-api#23]
Hi，I have installed python3-dev, python3-pip, python3-pyqt5.qtopengl, and vispy. However I fail to run the visualize.py. 
The code run well and  two windows popped out which I believe is the point cloud and the 2d picture. What went wrong is these windows stuck and seems transplant. And the terminal which run visualize.py print the following messages with vispy==0.6.1.

********************************************************************************
INTERFACE:
Dataset /mnt/staging/data_odometry_velodyne/dataset
Config config/labels/semantic-kitti.yaml
Sequence 00
Predictions None
ignore_semantics False
ignore_safety False
offset 0
********************************************************************************
Opening config file config/labels/semantic-kitti.yaml
Sequence folder exists! Using sequence from /mnt/staging/data_odometry_velodyne/dataset/sequences/00/velodyne
Labels folder exists! Using labels from /mnt/staging/data_odometry_velodyne/dataset/sequences/00/labels
WARNING: QOpenGLWidget: Failed to create context
WARNING: QOpenGLWidget: Failed to create context
Using semantics in visualizer
WARNING: QOpenGLWidget: Failed to create context
WARNING: QOpenGLWidget: Failed to create context
To navigate:
	b: back (previous scan)
	n: next (next scan)
	q: quit (exit program)
WARNING: composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed

![image](https://user-images.githubusercontent.com/13723009/68107231-1e5d2280-ff1f-11e9-90c9-4dac29ec0194.png)

If I downgrade the vispy to 0.5.3, the error message would be 

/usr/local/lib/python3.5/dist-packages/vispy/visuals/isourve.py:22: UserWarning: VisPy is not yet compatible with matplotlib 2.2+
  warnings.warn("VisPy is not yet compatible with matplotlib 2.2+")
********************************************************************************
INTERFACE:
Dataset /mnt/staging/data_odometry_velodyne/dataset/
Config config/labels/semantic-kitti.yaml
Sequence 00
Predictions None
ignore_semantics False
ignore_safety False
offset 0
********************************************************************************
Opening config file config/labels/semantic-kitti.yaml
Sequence folder exists! Using sequence from /mnt/staging/data_odometry_velodyne/dataset/sequences/00/velodyne
Labels folder exists! Using labels from /mnt/staging/data_odometry_velodyne/dataset/sequences/00/labels
Traceback (most recent call last):
  File "./visualize.py", line 147, in <module>
    instances=False)
  File "../../common/laserscanvis.py", line 27, in __init__
    self.reset()
  File "../../common/laserscanvis.py", line 37, in reset
    self.canvas = SceneCanvas(keys='interactive', show=True)
  File "/usr/local/lib/python3.5/dist-packages/vispy/scene/canvas.py", line 136, in __init__
    always_on_top, px_scale)
  File "/usr/local/lib/python3.5/dist-packages/vispy/app/canvas.py", line 205, in __init__
    self.create_native()
  File "/usr/local/lib/python3.5/dist-packages/vispy/app/canvas.py", line 222, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/vispy/app/backends/_qt.py", line 267, in __init__
    self._init_specific(p, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/vispy/app/backends/_qt.py", line 669, in _init_specific
    raise RuntimeError('context could not be created')
RuntimeError: context could not be created

And the program broke down. (For the warning "VisPy is not yet compatible with matplotlib 2.2+" I tried to downgrade matplitlib to 2.1, This warning disappear but the rest of error message remained.)

system: ubuntu 16.04.
tensorflow-gpu: 1.12.0
torch 0.4.1
torchvision 0.2.1
conda : Not installed

What linux version do you use?
Can you offer any help?

**Comment by BenjaminYoung29** [comment]
Hi. 

I've solved the problem. It turns out that it is the Windows' Remote Desktop Connection's problem. It doesn't support qt well. I use TeamViewer to connect my server and the program works!

**Comment by jbehley** [comment]
:+1: 

Thanks for letting us know.
