### ISSUE TITLE
Rename to semantic_kitti_api

### ISSUE THREAD

**Issue by jpaczia** [PRBonn/semantic-kitti-api#24]
Please rename the project to semantic_kitti_api, so it can be imported as a python module using `from semantic_kitti_api import *`
Modules with a hyphen in the name can not be imported, according to  [Stackoverflow](https://stackoverflow.com/questions/8350853/how-to-import-module-when-module-name-has-a-dash-or-hyphen-in-it).

Of course the directory can simply be renamed, but this way it would be more comfortable/elegant.

**Comment by jbehley** [comment]
Hi @jpaczia,

thanks for your interest in our work.

We will discuss your request, but currently your problem can be directly solved using:

`git clone https://github.com/PRBonn/semantic-kitti-api.git semantic_kitti_api`

which would clone the repository in the current working directory under `semantic_kitti_api`.

Hope that answers your issue.

**Comment by jbehley** [comment]
I close this issue now, since it seems to be easily resolvable without renaming our repository.
