### ISSUE TITLE
How to use multi-scan method

### ISSUE THREAD

**Issue by TT22TY** [PRBonn/semantic-kitti-api#25]
Hi, thanks for your code.

I wonder how to use multi-scan method, how to train with previous n scans, and how to evaluate the multiple-scan method?

**Comment by jbehley** [comment]
For the multi-scan case, it's up to you how you use the additional data. We used the poses and the data to generate a denser range image, but you could also generate a denser point clouds by aggregating multiple point clouds.

For evaluation, you have to provide labels for each separate scan, i.e, even if you use maybe 4 previous scans, you have to provide labels for only a single scan in the end. An example:

For infering the labels for scan t=4, you might use also scan t=3 and t=2, you still only generate labels for each point of scan t=4. The output is therefore the same as for the single-scan case: For each scan of the test set, you have to provide for each and every point a label.

The evaluation script is the same, but we furthermore evaluate the moving vs. non-moving classes. Therefore, we use here `config/semantic-kitti-all.yaml`for evaluation:

```
  ./evaluate_semantics.py 
     --datacfg config/semantic-kitti-all.yaml 
     --dataset /path/to/kitti/dataset/ 
     --predictions /path/to/method_predictions 
     --split train/valid/test
```

Hope that answers your question.

**Comment by TT22TY** [comment]
@jbehley  Thank you very much!
 Do you have plans to open source your code for handling the additional data , for example, generate a denser range image with multiple-scans and poses?

**Comment by jbehley** [comment]
Hi @TT22TY,

please see [generate_sequential.py](https://github.com/PRBonn/semantic-kitti-api/blob/master/generate_sequential.py) for the generation of accumulated scans. These are then used to get range image using the standard projection method inside Laserscan.

**Comment by TT22TY** [comment]
@jbehley thank you very much!
