### ISSUE TITLE
What does each column mean which in poses.txt file

### ISSUE THREAD

**Issue by hnsywangxin** [PRBonn/semantic-kitti-api#27]
@jbehley @tano297 
 Hello
I want to make my custom dataset through your annotation tools. Now, I have know how to generate the .bin files, but I don’t understand the file format of pose.txt.

What does each column mean which in poses.txt file

Can you give me a description such as "Each .bin scan is a list of float32 points in [x,y,z,remission] format"
Thank you very much!

**Comment by hnsywangxin** [comment]
I guess these 12 columns constitute the transformation matrix(3x4) which is from camera to velodyne. The first column corresponds to the index (0,0), and the last column corresponds to the index (2,3).
Is this the case?
Thank you !

**Comment by jbehley** [comment]
I answered the issue in the point labeler: https://github.com/jbehley/point_labeler/issues/12

Therefore I close this here.
