### ISSUE TITLE
Validation error using validate_submission.py

### ISSUE THREAD

**Issue by xiaodongyang** [PRBonn/semantic-kitti-api#28]
Hi, 

Thank you for sharing this great dataset and repo! I got this error using validate_submission.py to check for correct folder structure and consistent number of labels for each scan. Any suggestions? 

============ segmentation ============ 
  1. Checking filename.............. ✓
  2. Checking directory structure... ✓
  3. Checking file sizes............ 

  >>> Error: label file "sequences/11/predictions/000000.label' should have 16384 labels, but found 127405 labels!

**Comment by jbehley** [comment]
The only suggestion I have: Check that you provide for N points of the `.bin` file, also N labels in the `.label` file. The labels should be represented as `int32`.

If you want to check the submission for the scene completion task, you have to set the task accordingly with the validation script, i.e., 

```bash
./validate_submission.py --task completion <submission archive> <dataset path>
```

In case of scene completion, you have to provide for all voxels a label represented as `int16`

**Comment by xiaodongyang** [comment]
I'm running the segmentation task with your open-sourced code and necessary data downloaded, basically trying to reproduce your results. I think the error is caused by this https://github.com/PRBonn/semantic-kitti-api/blob/4036c9378f7653e10029c714ead8c78af5251cf2/validate_submission.py#L151

**Comment by jbehley** [comment]
Okay, I investigated the issue and in my last commit I accidently messed up the segmentation validation code. It should now work again.

Thanks for notifying me. Could you please verify that this  solves your problems?

**Comment by xiaodongyang** [comment]
Solved! Thanks for the quick action!
