### ISSUE TITLE
OSError: [Errno 30] Read-only file system: '/tmp/codalab/tmpJ31j8M'

### ISSUE THREAD

**Issue by munib94** [PRBonn/semantic-kitti-api#29]
Hi,

I made a submission for the single scan evaluation after successfully validating it using the validation script, but my submission failed and I received the following error:

    Traceback (most recent call last):
      File "/worker/worker.py", line 302, in run
        root_dir = tempfile.mkdtemp(dir=temp_dir)
      File "/usr/local/lib/python2.7/tempfile.py", line 339, in mkdtemp
        _os.mkdir(file, 0700)
    OSError: [Errno 30] Read-only file system: '/tmp/codalab/tmpJ31j8M'

I thought it might be a permission issue so I right clicked on my zip file, navigated to properties, and changed the permissions to "read and write" for all. However, after submitting again, I received the same error. Can you tell me what the issue is and how to fix it? My submissions are under the username munib94.

**Comment by jbehley** [comment]
The problem seems to be resolved. It appears that the codalab workers don't want to work on sunday, since COCO had yesterday the same problem: https://github.com/codalab/codalab-competitions/issues/2733: 

> I am participating COCO Detection Challenge (Bounding Box) https://competitions.codalab.org/competitions/20794#results and can not evaluate my results on test-dev 2019(bbox). The error information is given below. Can anyone tell me how to solve the problem or just give me a fake result example? Thanks so much!
> 
> Traceback (most recent call last):
> File "/worker/worker.py", line 302, in run
> root_dir = tempfile.mkdtemp(dir=temp_dir)
> File "/usr/local/lib/python2.7/tempfile.py", line 339, in mkdtemp
> _os.mkdir(file, 0700)
> OSError: [Errno 30] Read-only file system: '/tmp/codalab/tmpYQeYha'

I deleted your failed submissions and re-run your last submission. 

If you still experiencing issues, please let me know.

**Comment by whwu95** [comment]
@jbehley I received the same error: https://competitions.codalab.org/competitions/22217#participate-submit_results. Can you tell me what the issue is and how to fix it? My submissions are under the username KillerSeven.

**Comment by jbehley** [comment]
For future reference: I did not do anything and the problem was resolved. I suspect that the problem was just a missconfiguration of the cloud servers or something related.
