### ISSUE TITLE
about visualization on the whole sequence

### ISSUE THREAD

**Issue by amiltonwong** [PRBonn/semantic-kitti-api#3]
Hi, all,

We could [visualize](https://github.com/PRBonn/semantic-kitti-api#visualization) sequence on each scan basis.
Is there a tool to visualize the whole sequence like the output from Fig.8 in the paper? It'll be useful to visualize the entire sequence in a global view.

**Comment by tano297** [comment]
@jbehley can probably comment on this, as this visualization is part of another package

**Comment by jbehley** [comment]
No, we will not provide such tool. You will be able to visualize tiles with the point_labeler, but usually not the whole sequence. For smaller sequences, you could increase the tile size to get a visualization of the whole scene, but this will not work for 1000+ scans.

For Figure 8, I used every 20th scan and visualized everything as a single point cloud. You could get something similar with the python tool provided: Put all points in a single `.bin` file and the corresponding labels in single `.label` file, but use for the points the provided poses, such that the coordinates in the file are p' = T_t * p, where p corresponds to the original point at time t and T_t the pose at time t. A couple of lines python code should be sufficient.

**Comment by tano297** [comment]
Closing this for now, since it is not an issue. You can still comment on the thread if you need further help.
