### ISSUE TITLE
Where is the annotation data for Semantic Scene Completion task?

### ISSUE THREAD

**Issue by jingleFun** [PRBonn/semantic-kitti-api#31]
/kitti/dataset/
          └── sequences/
                  ├── 00/
                  │   ├── poses.txt
                  │   ├── image_2/
                  │   ├── image_3/
                  │   ├── labels/
                  │   │     ├ 000000.label
                  │   │     └ 000001.label
                  |   ├── voxels/
                  |   |     ├ 000000.bin
                  |   |     ├ 000000.label
                  |   |     ├ 000000.occluded
                  |   |     ├ 000000.invalid
                  |   |     ├ 000001.bin
                  |   |     ├ 000001.label
                  |   |     ├ 000001.occluded
                  |   |     ├ 000001.invalid
                  │   └── velodyne/
                  │         ├ 000000.bin
                  │         └ 000001.bin
                  ├── 01/
                  ├── 02/
                  .
                  .
                  .
                  └── 21/

--------------------------------------
Where can I download the voxels directorys ? Thank you.

**Comment by jbehley** [comment]
http://www.semantic-kitti.org/assets/data_odometry_voxels.zip

This link can be found on http://www.semantic-kitti.org/dataset.html#download

Let us know if you need further help.
