### ISSUE TITLE
Multiple Scan Experiment

### ISSUE THREAD

**Issue by munib94** [PRBonn/semantic-kitti-api#32]
For the multiple scan experiment in the SemanticKITTI paper, was the Darknet53Seg network also trained over the combined dataset (5-scans combined), or was it only evaluated over the 5-scan combined dataset? In other words, was it trained over the normal dataset, and then evaluated over the 5-scan combined dataset? I want to reproduce the results, but want to know that I am following the correct approach.

**Comment by jbehley** [comment]
Trained on aggregated scans (5 scans), evaluated on result for single scan. For the evaluation server you have to provide labels for each scan individually (including labels for moving traffic.)

**Comment by munib94** [comment]
So for the evaluation server, when I evaluate over Multiple Scans to obtain results for moving classes, does "Multiple Scans" imply that the dataset used for the evaluation server is aggregated (5 scans)?

**Comment by jbehley** [comment]
It takes the labels of a single scan as input. You can check our evaluation script for the validation set:

`./evaluate_semantics.py --datacfg config/semantic-kittti-all.yaml --dataset /path/to/kitti/dataset/ --predictions /path/to/method_predictions --split valid`

The only differcence between single scan and multiple scans is the configuration file, i.e., `config/semantic-kitti-all.yaml`. In the single scan case labels for moving objects are mapped to their static counterparts.

Hope that helps to clarify.

**Comment by munib94** [comment]
Thank you, that helps!
