### ISSUE TITLE
RuntimeError: Attached fragment shader is not compiled.

### ISSUE THREAD

**Issue by yanx27** [PRBonn/semantic-kitti-api#34]
Hi , I ran `visualize_voxels.py` according to your README, but got 
```Traceback (most recent call last):
  File "E:/Github/semantic-kitti-api/visualize_voxels.py", line 599, in <module>
    window = Window()
  File "E:/Github/semantic-kitti-api/visualize_voxels.py", line 108, in __init__
    self.initializeGL()
  File "E:/Github/semantic-kitti-api/visualize_voxels.py", line 212, in initializeGL
    self.program.link()
  File "E:\Github\semantic-kitti-api\auxiliary\glow.py", line 271, in link
    raise RuntimeError(str(msg.decode("utf-8")))
RuntimeError: Attached fragment shader is not compiled.

libpng warning: iCCP: cHRM chunk does not match sRGB
```

The library is same to `requirement.txt` and `OpenGL` is test well. Is there anyone can help me?

**Comment by jbehley** [comment]
Hi @yanx27,

we tested our software only under Ubuntu 18.04 and 16.04. Since you seem to use Windows, I cannot really tell what might be a problem. However, I suspect that it could be a problem either with path separators or line separators, but I could now give some advise how to fix it.

I will try to run the stuff under Windows, but it might take some time, since we are currently quite busy. If you can, you should give it a try under Ubunutu.

**Comment by VirtualRoyalty** [comment]
Hi! I had exactly the same problem yesterday. I also tried to run ' visualize_voxels.py-on Windows. After several hours of trying to solve this problem, I realize that perhaps OpenGL calculations are not happening on GPU. After switching all calculations to the GPU via Nvidia manager, the script started working! So you definitely have a chance to deploy this under Windows. I hope this helps you!

**Comment by jbehley** [comment]
Does the problem persist @yanx27 or can we close this issue?

**Comment by yanx27** [comment]
@jbehley Hi, I solve the problem when I change to Ubuntu~ Thank you for your help!

**Comment by luigui2906** [comment]
Hi..!
Thanks to @VirtualRoyalty. For people on Windows.. Open or download the NVIDIA Control Panel and go on the left bar to: **3D Settings > Manage 3D settings > Preferred graphics processor**. 

Change to **High-Performance NVIDIA processor**.

Best.

**Comment by ZepherusFF** [comment]
Hi @luigui2906 , Considering your comment on this post does it mean you managed to get it working on windows ? 
Could you share how you did this?

**Comment by luigui2906** [comment]
Hi @ZepherusFF,

Yes, I did what I indicated above. I attach an image to clarify. 

![image](https://user-images.githubusercontent.com/5257657/77566409-e94d6e80-6ec5-11ea-9c0c-4346b50c9616.png)


Good luck.

**Comment by ZepherusFF** [comment]
Hi @luigui2906 , ah yes I understood what you meant by the nvidia process, but I was more asking on the compilation part if you did anything peculiar? We tried and had couple issues and are gonna retry this week.

**Comment by luigui2906** [comment]
No. Nothing in particular, just installed the needed dependencies with either pip or conda (glfw, pyopengl, imgui).

I had the same error:

`raise RuntimeError(str(msg.decode("utf-8")))`
`RuntimeError: Attached fragment shader is not compiled.`

Just changed the configuration on the Nvidia Control Panel and then it was solved.

Let me know if you need something else.
