### ISSUE TITLE
Inquiry on paper details

### ISSUE THREAD

**Issue by kentangSJTU** [PRBonn/semantic-kitti-api#35]
Dear authors,

Thanks a lot for your open source code and SemanticKITTI dataset! After reading your ICCV'19 paper, I have some questions related to the statistics reported in Table 3.

- What is the hardware used to report these latency statistics?
- What network architecture do you use for PointNet / PointNet++? Is that the default architecture released by Charles Qi for segmentation tasks?
- Do you use sliding window to preprocess the data when using PointNet / PointNet++ or process the whole scene at one time? If you use the sliding window, what is the window size?

Great thanks for your reply!

Best,
Haotian

**Comment by jbehley** [comment]
1. I think we used an Nvidia Quadro P6000. 
2. We used the default architectures.
3. We downsampled to 50.000 or 45.000 points using random sampling (due to memory and time constraints). See Table 4 of the supplement.
.

**Comment by kentangSJTU** [comment]
Hi Jens,

Thanks for your reply! So that means, you actually do not divide the scene into sliding windows and process the whole scene at one time?

Best,
Haotian

**Comment by jbehley** [comment]
That's correct. We use the complete point cloud, subsample it, perform inference and assign the points without an label the nearest neighbor  label.

**Comment by kentangSJTU** [comment]
Hi Jens,

Thanks a lot for your detailed answer! It really solves my questions and I'm closing this issue.

Best,
Haotian
