### ISSUE TITLE
what is the size of a unit voxel cell? (in meter)

### ISSUE THREAD

**Issue by rancheng** [PRBonn/semantic-kitti-api#36]
Thanks for your contribution!

I saw the voxel size is `256x256x32`, but could you please also specify each voxel cell's size in meter.

https://github.com/PRBonn/semantic-kitti-api/blob/77d6e9b2ddd8ec334bf97651ffa68a75345b2796/auxiliary/SSCDataset.py#L34

**Comment by jbehley** [comment]
We used a voxel size  of 0.2 m.
