### ISSUE TITLE
Questions about the poses.txt in SemanticKITTI

### ISSUE THREAD

**Issue by jingyibo123** [PRBonn/semantic-kitti-api#39]
Hello,

For the official KITTI dataset, groundtruth poses were given, which I personally assume were generated from GPS/IMU results ?

The SemanticKITTI dataset also provided poses.txt, which
> contain the manually looped-closed poses for each capture (in the camera frame) that were used in the annotation tools to aggregate all the point clouds.

Can I ask if the generation of these poses include usage of the IMU/GPS raw data? Or merely via lidar/camera sensor odometry + manual loop closure?

Thanks a lot for answering.

**Comment by jbehley** [comment]
The poses for labeling and that we published are generated with our surfel-based SLAM approach which includes loop closures. Only on two sequences, we had to manually add loop closures. We do not use the KITTI poses. However, we still use the convention that the poses are represented in the camera coordinate system and therefore need to convert it via the calibration file to the LiDAR coordinate system.

**Comment by jingyibo123** [comment]
Thanks for the response!
I asked the question because I was surprised to see worse point cloud quality(in terms of multi-scan aggregation) from the KITTI groundtruth poses than the result I reproduced with Suma.
The following scene is from sequence 01, above is KITTI gt poses, below is Suma poses..

![Screenshot from 2020-03-30 15-53-18](https://user-images.githubusercontent.com/6594022/77888476-ee803400-729e-11ea-8cfb-95a2a9f98a9c.png)

![Screenshot from 2020-03-30 15-53-05](https://user-images.githubusercontent.com/6594022/77888485-f049f780-729e-11ea-8e92-759989ad3241.png)

The quality of multi-scan aggregation should be a direct indicatoro of relative pose accuracy, does that suggest that the "ground truth" poses provided by KITTI is not so perfect?

**Comment by jbehley** [comment]
We know that for loop closure regions the ground truth trajectory is not consistent. We also know that for some sequences the ground truth is obviously wrong due to supposedly a wrong initialization of the IMU (sequence 08). 

However, we have to account for the fact that we are using the "descewed" scans. It also might be that the IMU drifted here more. We simply don't know, what causes here the "blurry" results.

But that's the main reason, why we took estimated poses rather then simply the ground truth.

**Comment by jingyibo123** [comment]
Then the way I see it, the KITTI odometry evaluation and ranking could be quite biased, at least in terms of mid-range(200m) relative pose accuracy. 
Congratulations though on the great work with SuMa !
