### ISSUE TITLE
Issue creating own Data to Load

### ISSUE THREAD

**Issue by ZepherusFF** [PRBonn/semantic-kitti-api#40]
Hi ! 
Thanks for this great dataset, and labeling tool. 

We are trying to use the labeler to annotate data of our own, and are encountering weird issues. 

We have created the .bin files, .label files, the poses.txt and the calib.txt was retaken from sequence 04 (as I don't see the point of this file for annotating, but maybe I'm wrong, if so let me know). 

Here is how our points and labels are generated : 

        `#Points and Intensity
        points = np.column_stack((X,intensity))
        points =points.astype('f')
        points_string ="/Test/velodyne/00000%s.bin" % i
        points.tofile(points_string)

        #Labels
        labels = point_label.astype('uint32')
        label_string ="/Test/labels/00000%s.label" % i
        labels.tofile(label_string)`

The issue I am encountering when loading into the labeler, is that each pointcloud contains incorrect number of points (1287 instead of 35464 for example). This has been tested by loading one pointcloud, and looking at the two tiles containing points and looking at the labeler console for number of points. 

Another aspect is the visualisation of these points, This is what the points look like. This should be a Hesai 40 point cloud, so similar to standard Velodyne 64, yet it looks like nothing.
This makes me think of an incorrect typing, but I don't understand why as I've double checked the float32 types for the .bin and uint32 for the labels... 

![semantickitti](https://user-images.githubusercontent.com/4560248/77408570-393e0f80-6db8-11ea-9350-c489c9f2654c.png)

Does this ring a bell ? Is this a problem on the labeler, or more on our side ? If you have any ideas, I'm open to suggestions and testing, or I can explain more if needed ! 

Thanks again,

**Comment by jbehley** [comment]
The calibration file is needed as the poses of KITTI are stored in the camera coordinate system and we followed this convention with our files. Thus, when you take the calibration of sequences 04, the z axis will point forward, x right, y down. You can just take identity for the calibration file. (see also inside my code to convert to point labeler format in [kitti_raw2odometry.py](
https://github.com/jbehley/point_labeler/blob/805a35ce6cc29e0daa95bd91ab375fb308007154/scripts/kitti_raw2odometry.py#L156-L165))

The LiDAR files contain x,y,z, remission as floats (remission is in the range [0,1]). Thus, your file should have as size of  4 x N x 4 Bytes. (the file should be simply x,y,z,r,x,y,z,r, ....) The x-axis should point forward, y left, and z upwards.

The label files are generated automatically if they are not found.

**Comment by ZepherusFF** [comment]
hi @jbehley  Thanks for the quick answer ! 

I was indeed not using the calibration file/pose file correctly, which lead to all the points looking like that. 

Now we are having another issue which we struggle to understand... We are outputting our poses which is a continuous trajectory, using the identity for calibration file and we have a weird phenomenon where the aggregation is not done correctly (error in rotation/translation between clouds it seems like), but also, we have every 11 scans (2,13, 24,35,46 ) a "wrong" scan that gets displayed,  example below : 
![before](https://user-images.githubusercontent.com/4560248/77567996-3a5e6200-6ec8-11ea-91dd-795b2116bd39.jpg)
![after](https://user-images.githubusercontent.com/4560248/77567992-39c5cb80-6ec8-11ea-885f-3ff1d6a3b444.jpg)

Does this ring a bell by any chance.. ?

**Comment by jbehley** [comment]
I don't know.

I think it's either a problem of your poses or a problem with the storage of the scans.

use simply a pose file like this to see if your poses are wrong or your scans:

```python
f = open("poses.txt", "w")
for x in range(100): f.write(f"1 0 0 {x} 0 1 0 0 0 0 1 0\n")
f.close()
```

With this all scans should be on a straight line along the x axis. If now the 11th scan is still distorted its the way you generate the scans and if it's not distorted it's the way you generate the poses.

**Comment by ZepherusFF** [comment]
Hi @jbehley , we finally figured it out, it was due to the file names, where you expected : 
00000x.bin
0000yx.bin
000zyx.bin 

and I just wrote it as 00000zyx and so forth which caused unusual loading patterns. 
Writing it here in case anyone does same mistake !
