### ISSUE TITLE
Remission in SemanticKITTI

### ISSUE THREAD

**Issue by Sabze** [PRBonn/semantic-kitti-api#41]
Hi, 
Have you pre-processed the remission in any way? From the manual for Velodyne HDL 64E it looks like the remission/intensity is returned as an integer between 0 and 255, however in the SemanticKITTI dataset the remission is in the range 0-1. Have you just scaled the remission with 255, or have you done something else?

**Comment by jbehley** [comment]
we use the remission values provided by the KITTI Vision Benchmark. I think they are simply divided by 255, but a definitive answer can only give the maintainer of KITTI: Andreas Geiger.
