### ISSUE TITLE
Error on evaluate_completion.py

### ISSUE THREAD

**Issue by luigui2906** [PRBonn/semantic-kitti-api#43]
Hi,

I think there is an error on evaluate_completion.py, line 195:

https://github.com/PRBonn/semantic-kitti-api/blob/4e052eab2458befd3afd59e11724e7144acfe4cd/evaluate_completion.py#L195

the iouEval class at np_ioueval.py does not have this method.. I replaced this by 

`conf = evaluator.conf_matrix`

I guess you wanted to obtain the conf_matrix attribute of the class.

Best :)

**Comment by tano297** [comment]
@jbehley can you comment on this?

**Comment by jbehley** [comment]
Thanks for reporting this issue. Yes, the method is missing and it seems that it got somewhere in the transition from our private repo to the public github-hosted repo lost.
