### ISSUE TITLE
ask about panoptic segmentation task

### ISSUE THREAD

**Issue by amiltonwong** [PRBonn/semantic-kitti-api#44]
Hi, @jbehley ,

I know that some script for evaluating panoptic segmentation task is released. Could you give some brief introduction or guideline on how to use it?

THX!

**Comment by jbehley** [comment]
Please see https://github.com/PRBonn/semantic-kitti-api/blob/master/README.md#evaluation for an explanation.

**Comment by jbehley** [comment]
Let me know when you need additional information.
