### ISSUE TITLE
Moving object labels in semantic scene completion task

### ISSUE THREAD

**Issue by fcyeh** [PRBonn/semantic-kitti-api#48]
Why the moving car has this future trajectory labels? How can I just keep the current frame label for the moving object?
![gt_error_in3d](https://user-images.githubusercontent.com/26170029/82953389-888ef080-9f5f-11ea-893d-e9f73701ccef.PNG)

**Comment by jbehley** [comment]
This was a deliberate decision, which we tried to motivate in the following issue: https://github.com/jbehley/voxelizer/issues/2

**Comment by jbehley** [comment]
Did they other issue answer help you? If you still have concerns, reopen this issue.

**Comment by fcyeh** [comment]
> Did they other issue answer help you? If you still have concerns, reopen this issue.

Yes. This helps a lot. Thank you.
