### ISSUE TITLE
Voxelized data is shifted upwards

### ISSUE THREAD

**Issue by risteon** [PRBonn/semantic-kitti-api#49]
Dear authors of SemanticKITTI,
I've made the following observation:
The voxelized annotated point clouds (input grid, target grid, ...) are shifted one voxel upward due to a bug in the voxelizer `saveVoxelGrid` routine. This gets apparent when plotting the input point cloud together with the voxelized data.

See this pull request for the SemanticKITTI voxelizer:
https://github.com/jbehley/voxelizer/pull/4

**Comment by risteon** [comment]
> Luckily, the error did not invalidate the results from the metrics. I will write here, when I changed the data and everything is ready for download.

Did you already find the time to fix the data on the server? I'm unsure whether to submit with the 'old/shifted' voxel data or the 'new/fixed' data.

**Comment by jbehley** [comment]
As always, different other things needed my attention. I hope to find soon time to look at the issue. Sorry for the delay :(

**Comment by jbehley** [comment]
Hi @risteon,

I finally managed to take the time to regenerate the data. I visually verified that the data looks okay. I generate the data now with the correct counter.

Hope that resolves the issue then. You can now download the new data.

Bonus: I also now generate all scans for the training data which people now download.

**Comment by risteon** [comment]
Hi @jbehley,
thank you for updating the data - I had a look at it and it appears all right. I'm closing this issue now.
However, when submitting to the benchmark, I get a missing files error.
So I opened a new issue: https://github.com/PRBonn/semantic-kitti-api/issues/59
I don't now if it is related to the data update, I would appreciate it if you could take a look.
