### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by MartinHahner88** [PRBonn/semantic-kitti-api#5]
[http://www.semantic-kitti.org](http://www.semantic-kitti.org) is not reachable at the moment

**Comment by jbehley** [comment]
We know about the problem and hope that the DNS propagation will be finished soon. (see also https://dnschecker.org/#A/www.semantic-kitti.org).

You can use either a specific dns or modify your /etc/hosts. Or wait. ;)

**Comment by jbehley** [comment]
It seems like the problem is now resolved and all DNS servers have now the correct name resolution.
