### ISSUE TITLE
Multiple semantic labels for one single instance

### ISSUE THREAD

**Issue by alexa19lab** [PRBonn/semantic-kitti-api#51]
When I check your instance labels, I notice that there are cases where 3D points in one single instance have multiple semantic labels. For example, for points in one frame and with the same instance label, some of these points are semantically labeled with "car" while others labeled with "person". Could someone please explain that?

**Comment by jbehley** [comment]
Instance id are only unique within a class. Therefore, its possible to have instance 1 for car and instance 1 for person in the same scan. If you take the full 32 bits you have a unique identifier for object instances.

**Comment by alexa19lab** [comment]
Thanks so much for the reply! It solves my problem!
