### ISSUE TITLE
Temporally-consistent instance annotations

### ISSUE THREAD

**Issue by alexa19lab** [PRBonn/semantic-kitti-api#53]
In your paper, A Benchmark for LiDAR-based Panoptic Segmentation based on KITTI, it says, " We provide temporally-consistent instance annotations for all traffic participants including vehicles, pedestrians, bicyclists, and motorcyclists for the KITTI Odometry Benchmark." How do we understand "temporally-consistent"? For example, does one instance have identical 32 bit labels in sequential frames?

**Comment by jbehley** [comment]
Yes, That's the case. We tried to ensure that instances of the same class are the same over the whole sequence. No matter if they are non-moving or moving.

**Comment by alexa19lab** [comment]
Thanks for reply!
