### ISSUE TITLE
Codes for panoptic segmentation

### ISSUE THREAD

**Issue by chowkamlee81** [PRBonn/semantic-kitti-api#54]
Would like to know baseline code for panoptic segmentation on semantic kitti

**Comment by jbehley** [comment]
Sorry for the delay.

We used https://github.com/traveller59/second.pytorch to train on the KITTI data. The model is then applied to the KITTI scans to have the bounding box. The semantic segmentation is generated by your favorite model.

For merging the predictions, we use the following script: https://gist.github.com/jbehley/09591d1d8db400a5afc4a63eaeb026cd

**Comment by chowkamlee81** [comment]
Thanks got the idea. Closing the issue
