### ISSUE TITLE
CodaLab updating a submission with a paper link

### ISSUE THREAD

**Issue by mgerdzhev** [PRBonn/semantic-kitti-api#55]
Currently when you make a new submission you can add a link to a paper.
Is it possible to update an existing submission with a link to the paper? It only allows for changing the description, and no other fields.

**Comment by jbehley** [comment]
this information is currently not processed or available. we are working on a workaround. Currently, the only way to provide the paper is via our own leaderboard: http://semantic-kitti.org/tasks.html

I try to keep it updated, but you can contact me via email to let me know which paper needs to be added.
