### ISSUE TITLE
scene completion task - moving objects and point cloud aggregation

### ISSUE THREAD

**Issue by zgojcic** [PRBonn/semantic-kitti-api#56]
Dear authors, 

thanks for generating this great dataset. 

I was wondering if for the scene completion task the moving object are ignored while aggregating the future scans to one point cloud, or do you estimate also the per object transformation parameters for the moving objects? If the latter, are these transformation parameters available somewhere?

Thanks in advance.

Zan

**Comment by jbehley** [comment]
We decided to keep moving objects as a "spatio-temporal tube" in the data.

Please see also the discussion in https://github.com/jbehley/voxelizer/issues/2, which provides some insights from Martin.

However, I'm also open to handle this differently if there is some advantage of doing it differently.

**Comment by jbehley** [comment]
There is not much activity on this issue and I think it seems to be resolved. Therefore, I will now close this. If you still have doubts, please comment here or re-open the issue.
