### ISSUE TITLE
Warning: QOpenGLShaderProgram: could not create shader program

### ISSUE THREAD

**Issue by cak0** [PRBonn/semantic-kitti-api#6]
Hi there,
I followed the instructions and got visualization error when running this:
$ ./visualize.py --sequence 00 --dataset /path/to/kitti/dataset/

Two windows were created but only showed black visualization and some warnings popped up (see below).
Could you please help how to get it run properly?

Many thanks.

Print of warnings:
____________________________________
Opening config file config/semantic-kitti.yaml
./visualize.py:92: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  CFG = yaml.load(open(FLAGS.config, 'r'))
Sequence folder exists! Using sequence from /KITTI/kitti_odometry/sequences/04/velodyne
Labels folder exists! Using labels from /KITTI/kitti_odometry/sequences/04/labels
Using semantics in visualizer
To navigate:
	b: back (previous scan)
	n: next (next scan)
	q: quit (exit program)
WARNING: QOpenGLShaderProgram: could not create shader program
WARNING: QOpenGLShader: could not create shader
WARNING: bool QOpenGLTextureBlitter::create() Could not link shader program:
 ""
WARNING: QOpenGLShaderProgram: could not create shader program
WARNING: QOpenGLShader: could not create shader
WARNING: bool QOpenGLTextureBlitter::create() Could not link shader program:

**Comment by sarraghd** [comment]
hi,
I have a similar situation, I am using spyder(python 3.6) and pyqt5.9.2 on windows, two windows are created and did not show anything , I didn't get error or warning.

**Comment by jbehley** [comment]
Could you please provide some details on your system configuration, such that we can try to figure out what causes the problem?

Some information on Operating system, Python version, PyQt, OpenGl Version. What graphics device do you use?

The problem seems opengl related: do you have a working opengl   configuration: Please run `glxinfo` and provide the first lines with version and driver info, which you get on Ubuntu with `sudo apt install mesa-utils`.

**Comment by cak0** [comment]
Hi, I just repeated installing the requirements by re-running:
> sudo pip3 install -r requirements.txt
On top of confirming that many requirements are already satisfied, this also automatically downgraded some existing installations:
- vispy from 0.6.1 to 0.5.3 
- PyYAML from 5.1.2 to 5.1.1  

After that, I can see that the visualization now works just fine.
Hope it helps whoever encounters the same problem.
I'll close this issue now, thanks.

**Comment by jbehley** [comment]
Okay we may have to look at the vispy version... there seems to be a change.

The problem with PyYaml seems to be resolved.
