### ISSUE TITLE
scene completion: depth mapping from RGB image pixel coordinate to voxel coordinate

### ISSUE THREAD

**Issue by ashawkey** [PRBonn/semantic-kitti-api#60]
Hi,

In the paper, I see you also use RGB image in TS3D approach. I know how to map 2D pixel coordinate to 3D velodyne point cloud, but I'm a little confused at how to further map it to voxelized 3D volume. 

I'm assuming I should use voxelizer to generate the mapping from point cloud to 3D voxel coordinate. Could you give me some hints how to accomplish this?

Thanks!

**Comment by jbehley** [comment]
@mgarbade maybe can hopefully give more information on this.

**Comment by mgarbade** [comment]
@ashawkey Unfortunately I don't have a code solution for you at the moment, but here is the high level idea: 
There is a mapping between points in a laserscan and the corresponding rgb image. This can be found in this repository but also in the official repository of KITTI.
You can use that mapping to create laserscans that contain the label information for each image pixel (as far as I remember). 
Then you can use the [voxelizer](https://github.com/jbehley/voxelizer/) to generate the same voxels needed for training but containing the respective label information from the images.

**Comment by ashawkey** [comment]
Thanks for your reply! I will try your suggestion.
