### ISSUE TITLE
Evaluate by Distance Program

### ISSUE THREAD

**Issue by tsunghan-mama** [PRBonn/semantic-kitti-api#62]
To the best of my knowledge, data of each scan contains (x, y, z, intensity) four dimention information. Thus, I think only the first three dimension is needed when calculating depth. 
I would like to know if the code [here](https://github.com/PRBonn/semantic-kitti-api/blob/master/evaluate_semantics_by_distance.py#L201) is correct?
Thanks!

**Comment by jbehley** [comment]
Good catch. You are correct. I think it should be:

`depth = np.linalg.norm(scan[:, :3], 2, axis=1)  # get depth to filter by distance`

However, the intensity is as far as I remember in [0,1] and therefore I would not expect a big difference between the results. I still will change it for consistency.

**Comment by tsunghan-mama** [comment]
I think you're right. I've added it on and create a pr!

**Comment by jbehley** [comment]
I just merged it, thanks.
