### ISSUE TITLE
Does the dataset have reflection intensity information?

### ISSUE THREAD

**Issue by huixiancheng** [PRBonn/semantic-kitti-api#65]
As shown in the question.It's look like don't have.
Furthermore，will your team have the plan to annotation the image?
Since the KITTI dataset don't have big 2D sem.seg dataset.Ony one is a small dataset with 200 pics as I know.
looking forward to reply and thank your team’s for the great work!

**Comment by jbehley** [comment]
The original KITTI dataset provides remission for each lidar point. (The data is stored as x,y,z, remission).

We are currently working on a way to also provide image-based labels, but this is still in the early stages.

You should have a look at KITTI360 (http://www.cvlibs.net/datasets/kitti-360/index.php). On the semantic segmentation benchmark of KITTI, http://www.cvlibs.net/datasets/kitti/eval_semantics.php, there are also annotations from other researchers.

**Comment by huixiancheng** [comment]
Thanks, I'll try!Tribute to your team's work!
