### ISSUE TITLE
ques in the visualize.py

### ISSUE THREAD

**Issue by huixiancheng** [PRBonn/semantic-kitti-api#67]
Many thanks to your team for the open source code and toolbox，now I've tried to reproduce awesome early work with lidar-bonnetal.
And I have two ques about the visualize.py 

1. first is about the marked part 
![InkedQQ截图20201218144919_LI](https://user-images.githubusercontent.com/65054204/102584554-a44b2580-4141-11eb-95f3-fcd2e45c02f8.jpg)
Is this a part of #57 ？
The label of those points are "0" and mean "unlabeled" since there are 50m away.

2. second is about the config
there two semantickitti config.
one is 20 classes .one is 26 classes
I think the visualize.py don't use label mapping
the code and the result prove that
https://github.com/PRBonn/semantic-kitti-api/blob/c2d7712964a9541ed31900c925bf5971be2107c2/auxiliary/laserscan.py#L246-L247
https://github.com/PRBonn/semantic-kitti-api/blob/c2d7712964a9541ed31900c925bf5971be2107c2/auxiliary/laserscan.py#L263
![QQ截图20201218153723](https://user-images.githubusercontent.com/65054204/102587554-fcd0f180-4146-11eb-94a2-18c9a86300e6.png)

the rgb of the cyan part should be (0,0,0) since in semantic-kitti.yaml.  (50,255,255)👉（0，0，0）
https://github.com/PRBonn/semantic-kitti-api/blob/c2d7712964a9541ed31900c925bf5971be2107c2/config/semantic-kitti.yaml#L135

so i think the only useage of the config in the visualize.py is to provide the original 34 classes color_map.
https://github.com/PRBonn/semantic-kitti-api/blob/c2d7712964a9541ed31900c925bf5971be2107c2/visualize.py#L18-L24
I think it will lead to some misunderstandings.
Because the visualize.py show it's cyan but show scans during training and result of the predictions show it's black.  
At first I thought I had made a mistake in modifying the code since i am a noob :-)

**Comment by jbehley** [comment]
Sorry for the delay:

1. We only considered points up to 50 meters when labeling the point clouds. I think the visualization script does not account for unlabeled points.
2. You are right, we always visualize all classes. And note that the colors are BGR encoded in the configuration .yaml file.

The configuration files are mainly included showing how we evaluate on the server the single and multiple scan experiments. Therefore, we have to account for classes that are merged or ignored in the evaluation. 

Hope that answers your questions. Feel free to comment here if you still have doubts.

**Comment by huixiancheng** [comment]
ok,sir!thanks for you reply

**Comment by rockywind** [comment]
How visualize the point cloud in the server which are not a monitor?
