### ISSUE TITLE
Storing spherical projected scans and labels for training

### ISSUE THREAD

**Issue by ayushais** [PRBonn/semantic-kitti-api#7]
Hi, 

I can visualize the scans along with the labels. I also remapped the labels using remap_semantic_labels.py. How do I store the projected scans along with labels for training? Also for remap_semantic_labels.py I had to change the code to make it run. Mainly I had to specify a loader to loading the yaml file and change the datatypes for variables "key" and "data"

**Comment by ayushais** [comment]
More specifically I got these errors
remap_semantic_labels.py:85: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  DATA = yaml.load(open(FLAGS.datacfg, 'r'))

  File "remap_semantic_labels.py", line 102, in <module>
    if key > maxkey:
TypeError: '>' not supported between instances of 'str' and 'int'

**Comment by jbehley** [comment]
Could you provide us with some details on your development environment? It would help to know which operating system, python version, etc. you are using to reproduce the error.

In general, `remap_semantic_labels.py` reads the label files and converts our labels to labels in the range 0, 1, ...., 19. The script overwrites the label files with the new labels. There is no projection only a mapping from one label order to a different one.

For example, the original label 10 for car is mapped to 1, the label 30 for person is mapped to 6.

To get the spherical projections you have to take a look at `do_range_projection()` of `laserscan` in [auxiliary](https://github.com/PRBonn/semantic-kitti-api/tree/master/auxiliary)  which fills member variables of the laserscan object. These you can then store however you want.

**Comment by ayushais** [comment]
I am using Ubuntu 18.04 and Python 3.6.8. For other dependencies, I used the provided requirements file.

**Comment by jbehley** [comment]
Thanks for the info. I figured out the problem with PyYaml and it was related to the newest version, which deprecates the load function. Thanks for pointing this out.

Currently, I was not able to reproduce the second problem with the remap script. The yaml file contains integral numbers in the `learning` dict and therefore should be the key also `int`.

I will try to get the hands on Python 3.6 to see if there something changes.

**Comment by tano297** [comment]
Hello,

Using the provided config files, I have not been able to reproduce this behavior 

```
File "remap_semantic_labels.py", line 102, in 
if key > maxkey:
TypeError: '>' not supported between instances of 'str' and 'int'
```

In terms of the saving of the range representations for training, that is not related to the API but to range-based segmentation methods, so we will not add it to the API. I suggest you have a look in our other repo [LiDAR-bonnetal](https://github.com/PRBonn/lidar-bonnetal/), which has a [parser](https://github.com/PRBonn/lidar-bonnetal/blob/master/train/tasks/semantic/dataset/kitti/parser.py) dealing with the creation of laser scans and projection precisely for training range-based CNNs.

**Comment by ayushais** [comment]
Hey..thanks for pointing towards LiDAR-bonnetal. Maybe we can close the issue..since the error cannot be reproduced right now. We can look into it, if someone else reports a similar error.

**Comment by jbehley** [comment]
okay, we will do as you proposed. Thanks for your cooperation.
