### ISSUE TITLE
 how to obtain the laser number that each point is belong to？

### ISSUE THREAD

**Issue by xnozero** [PRBonn/semantic-kitti-api#72]
Hi,

I'm working on point cloud compression. Since the point clouds in SemanticKITTI are scanned by 64-way Laser Lidar, I wonder how to obtain the laser number that each point is belong to? I think this may be useful for compression.

Thanks!

**Comment by jbehley** [comment]
Hi,

sorry for the late reply.

Regarding your questions, there is no direct way of obtaining the id of the beam. You can try to use the angles to determine the ordering. But you have to consider the motion compensation of the point cloud. I noticed that the points are ordered in the way that points from a ring come after each other.

```python
import numpy as np
pts = np.fromfile("~/dataset/sequences/07/velodyne/000480.bin", dtype =np.float32)
print(pts.shape)

pts = pts.reshape(pts.shape[0]//4,4)

fig, ax = plt.subplots(figsize=(10,10))

num_points = pts.shape[0]
colors = np.array([[1,0,0]]*num_points)
colors[0:2048,:] = (0,1,0)
for i in range(num_points//2048):
    colors[i*2048:(i+1)*2048,:] = [(1,0,0), (0,1,0), (0,0,1), (0,1,1), (1,1,0), (1,0,1)][i%6]

ax.set_xlim(-50,50)
ax.set_ylim(-50,50)
ax.scatter(pts[:,0], pts[:, 1], s=0.2, c = colors)
```

Will give you something like this:


![image](https://user-images.githubusercontent.com/11506664/113058805-e6f3b380-91ae-11eb-9c7f-b48c0d3db296.png)


Thus you can see that the points are sequentially ordered in the ".bin" file. Thus, it should be possible to figure out with the yaw angle of a beam, when the "ring" changes. But I didn't investigate this further.

**Comment by xnozero** [comment]
Thank you for your help!

**Comment by HMX2013** [comment]
The ring number seems not complete right if you zoom the picture. Besides, why the the numbers of point of one ring is 2048. I think it should be 4500.

![Screenshot from 2023-02-15 10-35-08](https://user-images.githubusercontent.com/105980724/218912779-6cd8acc4-10a7-4f38-8645-5ddd7211f7b0.png)
