### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by Fraser-McLean** [PRBonn/semantic-kitti-api#73]
Hi, I have been experimenting with compressing point clouds (predominantly with PCL's Octree compression), and I have found that it significantly reduces the IoU that I can produce. The model I was using for reference generally get about 50%IoU, however with this any compression (and subsequent decompression) this reduces to about 3% - no matter the granularity of compression chosen. Further to this, even changing the .bin files to .pcd and back (without any other alteration) results in this same reduced performance. 

Is this normal behaviour due to reordering of the contents of the .bin files? or am I making a mistake somewhere with how I am converting the files?

edit: I have just check with another model and i get similarly poor results

**Comment by jbehley** [comment]
for the evaluation of the mioU, we consider only the order of the points. If you ensure that the ordering of the labels for the points is the same, it should be no problem.

if you use the points from the octree (a assume that the point coordinates change a bit), then it's normal that the learned model with the original coordinates should be a bit worse with the altered point cloud.

**Comment by Fraser-McLean** [comment]
It doesn't appear that there is any way to preserve the ordering of the point clouds when using octree. Thanks for the help anyway!
