### ISSUE TITLE
get tracks

### ISSUE THREAD

**Issue by ShengyuH** [PRBonn/semantic-kitti-api#74]
hi,

Thanks for providing this awesome toolbox. I am extracting the ground truth tracks for 3D tracking task. I use the following instance labels to associate objects across frames within the same sequence.

```
label = np.fromfile(path, dtype=np.uint32)
label = label.reshape((-1))
self.sem_labels = label & 0xFFFF  # semantic label in lower half, label & 65535
self.inst_labels = label >> 16    # instance id in upper half, label / 65536
```

However, if I then plot the length of each track(only keep those have less than 1000 frames for better visualisation), I get the following stats: 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/28732721/116857677-7f8db100-abfd-11eb-86f2-60ec521701b8.png">

The median and mean number of frames per track is 122 and 165 respectively, which means the same object can be tracked for around 12-16 seconds. Is this quite as expected or there's something wrong with my code?

Thanks in advance.

**Comment by jbehley** [comment]
Please note that only semantic label and instance id together are unique. There are cars and pedestrian which have instance id 1, etc. And you can use labels > 200 to get only 'moving' objects, i.e., objects that moved at some point when we annotated the tile.

As also static objects get consistent instance ids per class, it makes sense that many "short tracks" are present.

Hope that helps.

**Comment by ShengyuH** [comment]
Thanks for your prompt response.
