### ISSUE TITLE
Implementation of Darknet53Seg

### ISSUE THREAD

**Issue by MahmoudElkhateeb** [PRBonn/semantic-kitti-api#8]
Hello,
Are you plan to release the code of "Darknet53Seg" model that perform the best among others?

**Comment by jbehley** [comment]
We already have released code under [PRBonn/lidar-bonnetal](https://github.com/PRBonn/lidar-bonnetal), which was mainly developed by @tano297. There you will find also more information on the implementation and a framework for range-image-based semantic segmentation.

There you can find also a post-processing step (published in a follow-up work that will be presented at IROS 2019) that improves the DarkNet53 predictions quite a bit.

For pre-trained models, you can have a look at:
https://github.com/PRBonn/lidar-bonnetal/tree/master/train/tasks/semantic#semantickitti

**Comment by MahmoudElkhateeb** [comment]
Thanks a lot @jbehley  :)
