### ISSUE TITLE
Instance ID and visualization

### ISSUE THREAD

**Issue by Trainingzy** [PRBonn/semantic-kitti-api#84]
Thanks for your great contributions to the community!! Thanks for your dataset and toolbox. I have several questions about the dataset. 

The first one is about the instance id, do the instance id of a specific instance is temporal consistent across scans? In other words, one object has a same instance id across multiple consistent scans? And the instance id is the upper 16 bits of the `.label` file?

The second one is about visualization. How can we produce a visualization image like Fig 2 in [your ICCV paper](https://arxiv.org/pdf/1904.01416.pdf)? it seems the `visualize.py` you provide can only produce the projection image.

The third one is about lidar point clouds. I am new to this area, I notice that point clouds are sparse far from the center. I wonder if and how I could only collect the more denser points (close to the center) by processing your raw data.

Thank you again for your great work, look forward to your reply.

**Comment by jbehley** [comment]
1. For a specific class are the instance ids unique, i.e., the complete 32 integer is unique. In the Panoptic4D benchmark, we account for this and reassign instancesof different classes to make the instance ids unique.
2. with the provided pose information one can render the aggregated point clouds. When you open the point clouds in the point labeler, there is an option to also show single point clouds.
3. for the local point clouds you can only take points in a certain range, but loose the far range information.

**Comment by Trainingzy** [comment]
Thank you for your reply.

1. Do you mean the raw annotation is unique with 32 integers instead of the upper 16, since the semantic class is also considered for the instance label? Papers about panoptic segmentation indeed view the 32 integers as unique. However, in Panoptic4D code, they just use `ins_labels = frame_labels >> 16` as the instance label,  you mean they reassign the instance label, not the raw label?
2. Can I render the point clouds to get visualization video like [the video on YouTube](https://www.youtube.com/watch?v=VRZGAK3XpX0) with `visualize.py`? Btw, what does the pose mean?  If I want to use the temporal information, do I have to change the raw data with the pose? 
3. Intuitively, if I only take points in a certain range, I need to discard points of which the location is far from the center, so the center coordinates are (0,0,0)? Based on the second question, do I need to first change the point with the pose?

**Comment by Trainingzy** [comment]
Thank you for your patience and reply.

I think I understand the dataset much better now. One more question about the visualization, `visualize.py` is fine but I want to save the visualization results and put them on the paper, and use the visualization video as a demo.

Actually, I cannot find the `SuMa visualizer` you use on google. Can you share it with me?

**Comment by jbehley** [comment]
My modification is not public and as the visualizer of the surfel-based mapping is geared towards visualizing the SLAM approach, I currently don't feel like porting it.

However, you can work from the `visualize.py` and use the render method of the canvas (see https://vispy.org/api/vispy.app.canvas.html#vispy.app.canvas.Canvas.render) to produce an image. I usually save these images in a folder and then use ffmpeg to create a video from the images. For papers, I think using a white background is much better, but this is usually a matter of taste. Anyway, I usually make the point size a bit larger (like 2 or 3) to have better visibility in the paper.

hope that helps.

**Comment by Trainingzy** [comment]
Thank you very much for your answer. I will try it.
