### ISSUE TITLE
Pose Calculation

### ISSUE THREAD

**Issue by AlexSunNik** [PRBonn/semantic-kitti-api#88]
Hi, thanks for providing this nice codebase.

I was wondering whether the code to calculate the pose for projecting different frames is provided in this repo? thanks!

**Comment by jbehley** [comment]
If you want to project the point clouds into an image, you have to the transformations in the `calib.txt` and follow the instruction in the readme of the devkit provided by KITTI odometry (see http://www.cvlibs.net/datasets/kitti/eval_odometry.php)

If you want to use the poses to aggregate multiple scans based on the poses, you can have a look at https://github.com/PRBonn/semantic-kitti-api/blob/master/generate_sequential.py that does that.
