### ISSUE TITLE
save the visualization result as a point cloud file

### ISSUE THREAD

**Issue by chky1997** [PRBonn/semantic-kitti-api#89]
Hi, your visualization code is fantastic. I want to save the visualization result as a point cloud file for further exploration, is it possible?

**Comment by jbehley** [comment]
The point clouds are stored as a '.bin' file in the format of KITTI. If you want to have a different format that might include point coordinates but also semantics, then Open3D and  the ply format might be a good starting point. However, I cannot provide here support for this specifically, therefore, I close this issue as it is not directly related to the dataset itself.
