### ISSUE TITLE
generate_sequential.py extremely slow

### ISSUE THREAD

**Issue by alexkrz** [PRBonn/semantic-kitti-api#9]
Hi,
when I am running the generate_sequential.py script on one sequence with sequence_length=5, it takes extremely long until the corresponding binary file gets generated in the velodyne output folder. I have figured out that the struct.pack method in line 177 seems to be the bottleneck.
Do you have any suggestions how to address this issue?
I am running the semantic-kitti-api on Windows 10 with Python 3.6.8.
Cheers, 
Alex

**Comment by jbehley** [comment]
Hi @alexkrz,

I refactored the code a little bit. It now should run faster. If you still have problems, let us know.
