### ISSUE TITLE
Evaluation stuck on "Submitting" status

### ISSUE THREAD

**Issue by Jaehyun0818** [PRBonn/semantic-kitti-api#90]
Hi, Thanks for sharing the awesome dataset and the competition website. 
I submit my test result and It's successfully uploaded on the competition website.
However, my status is stuck on "Submitting" for 1 day. Is there any idea about this issue?
Thank you!

**Comment by jbehley** [comment]
Apparently, the submission queue of Codalab is currently a bit congested. Therefore, it might be that the submission currently takes some time. Re-submitting does currently not solve the problem but furthermore adds workload on the queue.

Hope that this will be resolved soon.

**Comment by jbehley** [comment]
the issue seems not relevant anymore. therefore, I close it.
