### ISSUE TITLE
NonType error

### ISSUE THREAD

**Issue by fenfenglitech** [PRBonn/semantic-kitti-api#92]
Error:
Traceback (most recent call last):
  File "/worker/worker.py", line 330, in run
    if input_rel_path not in bundles:
TypeError: argument of type 'NoneType' is not iterable

could you give me some suggestions?

**Comment by jbehley** [comment]
That's unfortunately very unspecific...

What do you try to execute or make?

**Comment by DayDayUpUpUp666** [comment]
I met the same error today，and how to solve it please
<img width="860" alt="微信图片_20211220171518" src="https://user-images.githubusercontent.com/23579491/146742967-c9b2d305-97cc-485b-a411-07c75b78b6b4.png">
？

**Comment by fenfenglitech** [comment]
Hi!
How long time can i get the score after submitted?

**Comment by jbehley** [comment]
I close this issue now, since it seems that the submissions got scored. If you encounter the error again, please reopen the issue again.
