### ISSUE TITLE
Is it possible to convert the segmentation labels to detection box?

### ISSUE THREAD

**Issue by zyl1336110861** [PRBonn/semantic-kitti-api#93]
As the title says.

**Comment by jbehley** [comment]
Hi @zyl1336110861,

as we provide instance level annotations, one can extract axis-aligned bounding boxes with classes. But for oriented bounding boxes, one needs to do some additional work as extracting the orientation with PCA is not working very well with partially occluded objects.

**Comment by zyl1336110861** [comment]
@jbehley Thanks for your response. So whether I can use the voxel labels instead of the direct point labels to finish the conversion from semantic to bounding box? I saw that there are extra voxels  added to the occluded objects.

**Comment by jbehley** [comment]
the occluded voxels are found via raytracing and cover the occluded area behind the car and not only the car.  I think it's not that easy to get reliable oriented bounding boxes without some manual effort. finding the orientation via PCA is not very reliable.

**Comment by jbehley** [comment]
It seems there is nothing more to discuss. If you feel still that there is an issue, then please reopen the issue.
