### ISSUE TITLE
strange data when printing .label file in semanticKITTI dataset

### ISSUE THREAD

**Issue by sugar1317** [PRBonn/semantic-kitti-api#95]
when i am tring to print each point's label, some points' label are very big such as 65791 , 14286858 , etc. Each scan has about 4000 to 6000 ,some even 8000. Does anybody else come across the same phenomenon.  it also occurs when i use cpp code to read the .label file.
![semanticKITTI中的异常](https://user-images.githubusercontent.com/61368890/155884193-f12807a0-5a0b-4c5b-a5ed-768f0ec0335f.png)

**Comment by jbehley** [comment]
Please note that the label is represented as an uint32, with the upper 16 bits corresponding to the instance id and the lower 16 bit to the semantic id. Also, note that the instance id is not unique over different classes. Only id + label is unique for each sequence.

Please read also the instructions and the provided scripts for more information.

Hope that clarifies the label format.

**Comment by fenfenglitech** [comment]
Hello!how can i get a view like the second figure without scrolling the mouse:
![saved_img0](https://user-images.githubusercontent.com/77180425/156124190-89ffb10f-5f5f-4f17-8742-49cb84dbf158.png)
![saved_img1](https://user-images.githubusercontent.com/77180425/156124255-060b4aaa-0164-412c-866e-091645b3893f.png)
<img width="404" alt="small_figure" src="https://user-images.githubusercontent.com/77180425/156124870-848f48c1-1eb5-4905-991b-d33c89d0fbc0.PNG">

**Comment by fenfenglitech** [comment]
@jbehley 
Hello!what parameters can be changed, that i can get a view like the second figure without scrolling the mouse:
![saved_img0](https://user-images.githubusercontent.com/77180425/156124190-89ffb10f-5f5f-4f17-8742-49cb84dbf158.png)
<img width="404" alt="small_figure" src="https://user-images.githubusercontent.com/77180425/156124870-848f48c1-1eb5-4905-991b-d33c89d0fbc0.PNG">

**Comment by jbehley** [comment]
Please refer to the vispy documentation. I guess you can set the camera specifically with the `camera` parameter of the viewbox widget: https://vispy.org/api/vispy.scene.widgets.viewbox.html

I think the issue can now be closed as the initial problem seems to be resolved. If you still experience problems, then simply reopen the issue again.
