### ISSUE TITLE
How can I get depth image from SemanticKITTI

### ISSUE THREAD

**Issue by Kaisyouu** [PRBonn/semantic-kitti-api#99]
Hi, all.

How can I get depth image from SemanticKITTI?

**Comment by Guru-Deep-Singh** [comment]
SemanticKITTI contains sequences from the odometry dataset of KITTI vision suit. If you check the readme of dev kit for the odometry dataset it tells you the mapping between the odometry sequence and the raw data, see image attached.
![Capture](https://user-images.githubusercontent.com/68775950/161446112-29363bcb-24e4-4bd8-ba59-19ba42428353.PNG)


Once you know this mapping just sample these sequences from the kitti depth benchmark. Voila!! you have the SemanticKITTI depth maps.

**Comment by jbehley** [comment]
You can use a range image projection as described in our paper: 

J Behley et al. Efficient Surfel-Based SLAM using 3D Laser Range Data in Urban Environments, RSS, 2018. http://www.roboticsproceedings.org/rss14/p16.pdf. 

See equation 2.  I think this medium article: https://towardsdatascience.com/spherical-projection-for-point-clouds-56a2fc258e6c provides some more detailed description (but I did not check this). You can also use the code: https://github.com/PRBonn/semantic-kitti-api/blob/master/auxiliary/laserscan.py to get the projection.

There are also other ways to get a range image projection from KITTI that also accounts for the motion distortion included: 

L Triess et al. Scan-based Semantic Segmentation of LiDAR Point Clouds: An Experimental Study. IEEE Intelligent Vehicles Symposium (IV), 2020. see https://arxiv.org/pdf/2004.11803.pdf


hope that helps.
